/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness probe */
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/version": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Version + capabilities */
        get: operations["version"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Parse a vector file into wiaConstructor geometry
         * @description Accepts the bytes of a DXF, SVG, HPGL, NGC, STL or other supported
         *     format and returns the flattened geometry: layers, segments
         *     (LINE/ARC primitives with bulge for arcs), bounding box, and unit
         *     scale.
         */
        post: operations["import"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generate gcode + 3D toolpath preview from imported geometry
         * @description Stub for Stage-1; full setup-tree input lands in d0d follow-ups.
         */
        post: operations["generate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/defaults": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Setup-tree JSON Schema (drives the form UI) */
        get: operations["defaults"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        BBox: {
            /** Format: double */
            max_x: number;
            /** Format: double */
            max_y: number;
            /** Format: double */
            min_x: number;
            /** Format: double */
            min_y: number;
        };
        DefaultsResponse: {
            schema: unknown;
            setup: components["schemas"]["Setup"];
        };
        Error: {
            details?: unknown;
            error: string;
        };
        /** @description Pipeline input. Tabs are keyed by *imported-segment* index (the key the frontend uses when tracking placed tabs); we resolve each tab to its containing chain object internally. */
        GenerateRequest: {
            post_processor?: components["schemas"]["PostProcessorKind"] | null;
            segments: components["schemas"]["Segment"][];
            setup?: components["schemas"]["Setup"] | null;
            tabs?: {
                [key: string]: components["schemas"]["TabPoint"][];
            };
        };
        GenerateResponse: {
            gcode: string;
            stats: components["schemas"]["PipelineStats"];
            toolpath: components["schemas"]["ToolpathSegment"][];
        };
        GenerateStats: {
            /** Format: uint */
            closed_object_count: number;
            /** Format: uint */
            object_count: number;
            /** Format: uint */
            offset_count: number;
        };
        HealthResponse: {
            ok: boolean;
        };
        ImportResponse: {
            bbox: components["schemas"]["BBox"];
            filename: string;
            format: string;
            layers: components["schemas"]["Layer"][];
            segments: components["schemas"]["Segment"][];
            /** Format: double */
            unit_scale: number;
            warnings: string[];
        };
        Layer: {
            /** Format: int32 */
            color: number;
            name: string;
            /** Format: uint */
            segment_count: number;
        };
        /** @enum {string} */
        LeadKind: "off" | "straight" | "arc";
        LeadsConfig: {
            in: components["schemas"]["LeadKind"];
            /** Format: double */
            in_lenght: number;
            out: components["schemas"]["LeadKind"];
            /** Format: double */
            out_lenght: number;
        };
        MachineConfig: {
            /** @description Whether the machine emits arc commands (G2/G3). */
            arcs: boolean;
            comments: boolean;
            mode: components["schemas"]["MachineMode"];
            supports_toolchange: boolean;
            unit: components["schemas"]["UnitSystem"];
        };
        /** @enum {string} */
        MachineMode: "mill" | "laser" | "drag";
        MillConfig: {
            active: boolean;
            /** Format: double */
            depth: number;
            /** Format: double */
            fast_move_z: number;
            helix_mode: boolean;
            objectorder: components["schemas"]["ObjectOrder"];
            offset: components["schemas"]["ToolOffset"];
            /**
             * @description When true, dip into sharp inner corners so the cutter fully clears them. Mirrors viaConstructor's `mill.overcut`.
             * @default false
             */
            overcut: boolean;
            reverse: boolean;
            /** Format: double */
            start_depth: number;
            /**
             * Format: double
             * @description Per-pass z step (negative ⇒ down).
             */
            step: number;
        };
        /** @enum {string} */
        ObjectOrder: "nearest" | "per_object" | "unordered";
        PipelineStats: {
            /** Format: uint */
            closed_object_count: number;
            /** Format: uint */
            object_count: number;
            /** Format: uint */
            offset_count: number;
        };
        PocketConfig: {
            active: boolean;
            insideout: boolean;
            islands: boolean;
            /** @description Skip the boundary contour pass (used by HATCH-equivalent layers). */
            nocontour: boolean;
            zigzag: boolean;
        };
        Point2: {
            /** Format: double */
            x: number;
            /** Format: double */
            y: number;
        };
        /** @description One concentric offset of a closed object — used for both the boundary pass and any inward pocket cascade rings. */
        PolylineOffset: {
            closed: boolean;
            /** Format: int32 */
            color: number;
            /**
             * Format: uint8
             * @description 0 = boundary, 1 = zigzag fill stroke, 2 = pocket ring.
             */
            is_pocket: number;
            layer: string;
            /**
             * Format: uint32
             * @description 0 = outer boundary, 1+ = pocket cascade inward.
             */
            level: number;
            segments: components["schemas"]["Segment"][];
            /** Format: uint */
            source_object_idx: number;
            /** @description Tab positions (data-space XY) the cutter should lift over while cutting this offset. Frontend places these via mtm.10; the gcode emitter splits the cut at each crossing and lifts Z to tabs.height. */
            tabs?: components["schemas"]["TabPoint"][];
        };
        Pose3: {
            /** Format: double */
            x: number;
            /** Format: double */
            y: number;
            /** Format: double */
            z: number;
        };
        /** @enum {string} */
        PostProcessorKind: "linuxcnc" | "grbl" | "hpgl";
        /** @description A flat LINE/ARC primitive. ARC geometry is encoded as the bulge between `start` and `end` (bulge = `tan(included_angle / 4)`). */
        Segment: {
            /**
             * Format: double
             * @default 0
             */
            bulge: number;
            center?: components["schemas"]["Point2"] | null;
            /**
             * Format: int32
             * @default 7
             */
            color: number;
            end: components["schemas"]["Point2"];
            /** @default 0 */
            layer: string;
            start: components["schemas"]["Point2"];
            type: components["schemas"]["SegmentKind"];
        };
        /** @enum {string} */
        SegmentKind: "LINE" | "ARC" | "CIRCLE" | "POINT";
        Setup: {
            leads: components["schemas"]["LeadsConfig"];
            machine: components["schemas"]["MachineConfig"];
            mill: components["schemas"]["MillConfig"];
            pockets: components["schemas"]["PocketConfig"];
            tabs: components["schemas"]["TabsConfig"];
            tool: components["schemas"]["ToolConfig"];
        };
        TabPoint: {
            /** Format: double */
            x: number;
            /** Format: double */
            y: number;
        };
        /** @enum {string} */
        TabType: "rectangle" | "ramp";
        TabsConfig: {
            active: boolean;
            /** Format: double */
            height: number;
            tab_type: components["schemas"]["TabType"];
            /** Format: double */
            width: number;
        };
        ToolConfig: {
            /** Format: double */
            diameter: number;
            /**
             * Format: double
             * @description Drag-knife offset (if present, otherwise None).
             */
            dragoff?: number | null;
            flood: boolean;
            mist: boolean;
            /** Format: uint32 */
            number: number;
            /**
             * Format: uint32
             * @description Spindle warm-up pause in seconds.
             */
            pause: number;
            /**
             * Format: uint32
             * @description Cutting feedrate (mm/min).
             */
            rate_h: number;
            /**
             * Format: uint32
             * @description Plunge feedrate (mm/min).
             */
            rate_v: number;
            /** Format: uint32 */
            speed: number;
        };
        /** @enum {string} */
        ToolOffset: "none" | "outside" | "inside" | "on";
        ToolpathSegment: {
            from: components["schemas"]["Pose3"];
            kind: components["schemas"]["SegmentKind"];
            to: components["schemas"]["Pose3"];
        };
        /** @enum {string} */
        TransportKind: "python-bridge" | "rust-server" | "tauri" | "wasm";
        /** @enum {string} */
        UnitSystem: "mm" | "inch";
        /** @description `VcObject` analogue: a chain of segments grouped after `segments2objects`. */
        VcObject: {
            closed: boolean;
            /** Format: int32 */
            color: number;
            /** @description IDs of objects fully contained by this one. */
            inner_objects: number[];
            layer: string;
            /** @description IDs of objects fully containing this one. */
            outer_objects: number[];
            /**
             * Format: double
             * @description Per-object override of the tool-radius offset (None ⇒ tool diameter / 2).
             */
            overwrite_offset?: number | null;
            segments: components["schemas"]["Segment"][];
            /** @description Per-object setup overrides (mill depth, leads, tabs, …). */
            setup: components["schemas"]["Setup"];
            /** @description Optional starting point for cut-order seeding. */
            start?: components["schemas"]["Point2"] | null;
            /** @description "outside" / "inside" / "none" — see `setup::ToolOffset`. */
            tool_offset: components["schemas"]["ToolOffset"];
        };
        VersionResponse: {
            capabilities: string[];
            transport: components["schemas"]["TransportKind"];
            version: string;
        };
    };
    responses: {
        /** @description Malformed input */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Could not parse content */
        UnprocessableEntity: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service is up */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    version: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VersionResponse"];
                };
            };
        };
    };
    import: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    file: string;
                    /** @description Optional explicit format hint (dxf|svg|hpgl|ngc|stl). Inferred from filename otherwise. */
                    format?: string;
                };
            };
        };
        responses: {
            /** @description Parsed geometry */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            422: components["responses"]["UnprocessableEntity"];
        };
    };
    generate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GenerateRequest"];
            };
        };
        responses: {
            /** @description Generated output */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenerateResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    defaults: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Default setup tree + JSON Schema for the form UI */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DefaultsResponse"];
                };
            };
        };
    };
}
