/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness probe */
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/version": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Version + capabilities */
        get: operations["version"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Parse a vector file into wiaConstructor geometry
         * @description Accepts the bytes of a DXF, SVG, HPGL, NGC, STL or other supported
         *     format and returns the flattened geometry: layers, segments
         *     (LINE/ARC primitives with bulge for arcs), bounding box, and unit
         *     scale.
         */
        post: operations["import"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generate gcode + 3D toolpath preview from imported geometry
         * @description Stub for Stage-1; full setup-tree input lands in d0d follow-ups.
         */
        post: operations["generate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/text": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Render TTF text into geometry segments
         * @description Tessellates a TTF/OTF font + a string into the project's standard
         *     Segment shape. Used by the Add-Text dialog. The response also
         *     carries a `single_line` flag derived by `is_single_line_font` so
         *     the dialog can warn when a filled-outline font is paired with the
         *     Engraving style.
         */
        post: operations["renderText"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        BBox: {
            /** Format: double */
            max_x: number;
            /** Format: double */
            max_y: number;
            /** Format: double */
            min_x: number;
            /** Format: double */
            min_y: number;
        };
        /** @enum {string} */
        Coolant: "off" | "mist" | "flood";
        /**
         * @description Climb vs conventional milling. Determines the path winding the generator emits — for a standard right-hand spindle:
         *
         *     | context (cutter location) | conventional      | climb              | |---------------------------|-------------------|--------------------| | outer (cutter outside)    | CW (area < 0)     | CCW (area > 0)     | | inner (cutter in pocket)  | CCW (area > 0)    | CW (area < 0)      |
         *
         *     "Conventional" is the safer default — most hobby and older mills don't have the rigidity / backlash takeup needed for clean climb cuts. Climb gives a better surface finish but requires a stiff machine. The finishing pass typically stays conventional regardless of the main strategy because the finish wall quality matters most.
         * @enum {string}
         */
        CutDirection: "conventional" | "climb";
        /** @description Drill-cycle picker for [`OperationKind::Drill`]. Mirrors the canned cycles G81 / G83 / G73 from the LinuxCNC / Fanuc dialect plus the dwell-at-bottom parameter PyCAM's `Drilling.py` exposes. Posts that don't support canned cycles fall back to a manual G0/G1 expansion of the same cycle (see `PostProcessor::drill_*` defaults). */
        DrillCycle: {
            /**
             * Format: double
             * @description Dwell at bottom in seconds before retract. 0 = no dwell.
             * @default 0
             */
            dwell_sec: number;
            /** @enum {string} */
            kind: "simple";
        } | {
            /**
             * Format: double
             * @default 0
             */
            dwell_sec: number;
            /** @enum {string} */
            kind: "peck";
            /** Format: double */
            peck_step_mm: number;
        } | {
            /**
             * Format: double
             * @default 0
             */
            dwell_sec: number;
            /** @enum {string} */
            kind: "chip_break";
            /** Format: double */
            peck_step_mm: number;
        };
        Error: {
            details?: unknown;
            error: string;
        };
        /**
         * @description Shape of the synthetic frame built around a Pocket-Outside selection. Rectangle is a plain padded bbox; RoundedRectangle uses the same bbox with a quarter-arc bulge at each corner. Oval and TightOutline are explicit follow-ups — not in v1.
         * @enum {string}
         */
        FrameShape: "rectangle" | "rounded_rectangle";
        /** @description Lookup table the frontend uses to wire the gcode text panel to the 3D toolpath: line N in the gcode corresponds to `segments[lines_to_segment[N]]`, and `segments_to_line[i]` is the 1-based gcode line that produced segment `i`. Both vectors are dense — gcode lines that don't move the tool map to `usize::MAX` so callers can detect the gap. */
        GcodeIndex: {
            lines_to_segment: number[];
            segments_to_line: number[];
        };
        GenerateRequest: {
            post_processor?: components["schemas"]["PostProcessorKind"] | null;
            /** @description The full project — geometry + machine + tools + operations + tabs. */
            project: components["schemas"]["Project"];
        };
        GenerateResponse: {
            gcode: string;
            gcode_index: components["schemas"]["GcodeIndex"];
            /** @description Filled-area preview for Pocket ops: the actual region the cutter will machine, computed via the per-op SourceCombine mode (Auto by default — outer + inner = annulus). The frontend paints these as translucent fills so the user sees what they're cutting before reading the toolpath. Empty for non-Pocket ops. */
            regions?: components["schemas"]["RegionPreview"][];
            stats: components["schemas"]["PipelineStats"];
            toolpath: components["schemas"]["ToolpathSegment"][];
            /** @description Non-fatal warnings raised during planning — mostly tool-fit problems (cutter doesn't fit the geometry, kind mismatch, …). The frontend surfaces these in the operations list status badge and a sidebar list; the gcode is still emitted. */
            warnings?: components["schemas"]["PipelineWarning"][];
        };
        GenerateStats: {
            /** Format: uint */
            closed_object_count: number;
            /** Format: uint */
            object_count: number;
            /** Format: uint */
            offset_count: number;
        };
        HealthResponse: {
            ok: boolean;
        };
        ImportResponse: {
            bbox: components["schemas"]["BBox"];
            filename: string;
            format: string;
            layers: components["schemas"]["Layer"][];
            /**
             * @description Object metadata (closed flag, layer, color, bbox) keyed by the same 1-based id — `object_meta[id - 1]` is the entry for object `id`.
             * @default []
             */
            object_meta: components["schemas"]["ImportedObject"][];
            /**
             * @description Per-segment object id from the chaining pass — `objects[i]` is the 1-based id of the chained object that consumed `segments[i]` (0 means "didn't chain into any object", e.g. an isolated point). The frontend uses this to do object-level selection in 2D.
             * @default []
             */
            objects: number[];
            segments: components["schemas"]["Segment"][];
            /** Format: double */
            unit_scale: number;
            warnings: string[];
        };
        ImportedObject: {
            bbox: components["schemas"]["BBox"];
            closed: boolean;
            /** Format: int32 */
            color: number;
            /** Format: uint32 */
            id: number;
            layer: string;
        };
        Layer: {
            /** Format: int32 */
            color: number;
            name: string;
            /** Format: uint */
            segment_count: number;
        };
        /** @enum {string} */
        LeadKind: "off" | "straight" | "arc";
        LeadsConfig: {
            in: components["schemas"]["LeadKind"];
            /**
             * Format: double
             * @description Lead-in size. Interpreted by `LeadKind`: * `Straight`: straight-line LENGTH (mm) of the approach. * `Arc`: tangent roll-on arc RADIUS (mm). The arc sweeps a quarter turn from the approach point (radius away on the perpendicular) to the contour start, landing tangent to the first cut segment. * `Off`: ignored.
             */
            in_lenght: number;
            out: components["schemas"]["LeadKind"];
            /**
             * Format: double
             * @description Lead-out size. Same interpretation as `in_lenght` but applied at the END of the cut path (cutter rolls off the contour at Pn).
             */
            out_lenght: number;
        };
        MachineConfig: {
            /** @description Whether the machine emits arc commands (G2/G3). */
            arcs: boolean;
            comments: boolean;
            mode: components["schemas"]["MachineMode"];
            supports_toolchange: boolean;
            unit: components["schemas"]["UnitSystem"];
        };
        /** @enum {string} */
        MachineMode: "mill" | "laser" | "drag";
        MillConfig: {
            active: boolean;
            /**
             * Format: double
             * @description When > 0, slow the feedrate at sharp line-to-line corners by this fraction so the machine doesn't dwell on the corner with high accel demand. 0.0 = no reduction (current behavior). 0.5 = half the feed at corners. Most useful for zigzag pocket fills with their many 180° turns.
             * @default 0
             */
            corner_feed_reduction: number;
            /** Format: double */
            depth: number;
            /**
             * @description Explicit ordered list of Z depths to cut at. When non-empty, overrides the step / finish_step / through_depth schedule.
             * @default []
             */
            depth_list: number[];
            /** Format: double */
            fast_move_z: number;
            /**
             * Format: double
             * @description Optional smaller step for the FINAL Z pass (cleaner bottom finish). None = use `step` for every pass.
             * @default null
             */
            finish_step: number | null;
            helix_mode: boolean;
            objectorder: components["schemas"]["ObjectOrder"];
            offset: components["schemas"]["ToolOffset"];
            /**
             * @description When true, dip into sharp inner corners so the cutter fully clears them. Mirrors viaConstructor's `mill.overcut`.
             * @default false
             */
            overcut: boolean;
            /**
             * @description How the cutter descends into material at the start of each Z pass. `Direct` is a straight plunge; `Ramp` walks the first `ramp_length` of the path while linearly descending Z so the cutter takes a chip in both Z and XY simultaneously.
             * @default {
             *       "kind": "direct"
             *     }
             */
            plunge: components["schemas"]["PlungeStrategy"];
            reverse: boolean;
            /** Format: double */
            start_depth: number;
            /**
             * Format: double
             * @description Per-pass z step (negative ⇒ down).
             */
            step: number;
            /**
             * Format: double
             * @description Cut past `depth` by this many mm (positive). Used for through-cuts on edge-clamped sheet.
             * @default 0
             */
            through_depth: number;
        };
        /** @enum {string} */
        MoveKind: "rapid" | "cut" | "plunge" | "retract" | "arc";
        /** @enum {string} */
        ObjectOrder: "nearest" | "per_object" | "unordered";
        Operation: {
            enabled: boolean;
            /** Format: uint32 */
            id: number;
            kind: components["schemas"]["OperationKind"];
            name: string;
            params: components["schemas"]["OperationParams"];
            /** @description Optional pattern repetition. When set, the op runs once per pattern instance with the source geometry translated/rotated. See [`PatternConfig`] for the concrete pattern shapes. */
            pattern?: components["schemas"]["PatternConfig"] | null;
            source: components["schemas"]["OperationSource"];
            /**
             * Format: uint32
             * @description id of a `Project.tools` entry.
             */
            tool_id: number;
        };
        OperationKind: {
            offset: components["schemas"]["ToolOffset"];
            /** @enum {string} */
            type: "profile";
        } | {
            strategy: components["schemas"]["PocketStrategy"];
            /** @enum {string} */
            type: "pocket";
        } | {
            cycle: components["schemas"]["DrillCycle"];
            /** @enum {string} */
            type: "drill";
        } | {
            /** @enum {string} */
            type: "thread";
        } | {
            /** @enum {string} */
            type: "chamfer";
        } | {
            /** @enum {string} */
            type: "engrave";
        } | {
            /** @enum {string} */
            type: "drag_knife";
        } | {
            /** @enum {string} */
            type: "helix";
        } | {
            /** @enum {string} */
            type: "v_carve";
        };
        OperationParams: {
            /**
             * Format: double
             * @description V-Carve cap on the inscribed-circle radius (mm). When set, any medial-axis point with `R_inscribed > carve_max_width_mm` clips to the cap — the V doesn't carve any wider than the bit's usable diameter. None = no cap (use the geometric inscribed circle directly).
             */
            carve_max_width_mm?: number | null;
            /**
             * Format: double
             * @description When > 0, slow the feed at sharp corners by this fraction so the machine doesn't dwell on the corner with high accel demand. 0.0 = no reduction (current behavior). 0.5 = half the feed at corners. Most useful for zigzag pocket fills with their many 180° turns.
             */
            corner_feed_reduction?: number;
            /** @description Cut direction for the main (roughing) passes. Default: Conventional. See [`CutDirection`] for the winding rules. */
            cut_direction?: components["schemas"]["CutDirection"];
            /**
             * Format: double
             * @description Final cut depth (negative number — a depth, not a height).
             */
            depth: number;
            /** @description Explicit list of Z depths for each pass, overriding the step+finish_step schedule. Useful for non-linear schedules (shallower at start for tough material, deeper later, slow finish at the end). Each entry is an absolute Z (negative number); the cutter visits them in order. Empty = use the step-down loop. */
            depth_list?: number[];
            /**
             * Format: double
             * @description Z for rapid moves between cuts.
             */
            fast_move_z: number;
            /**
             * Format: uint32
             * @description Override the tool's `feed_rate` for this op only. Some materials or finishing passes need a slower feed than the tool's default; rather than editing the tool library, set this per-op. None = use the tool's `feed_rate`. Units: mm/min.
             */
            feed_rate_override?: number | null;
            /** @description Cut direction for the finishing pass — the offset that defines the wall surface (Pocket level=0 ring; Profile single-pass cut). Default: Conventional, regardless of the main `cut_direction`. Surface quality on the finish wall is almost always best with conventional milling on hobby machines. */
            finish_cut_direction?: components["schemas"]["CutDirection"];
            /**
             * Format: double
             * @description Optional smaller step for the FINAL Z pass, for a cleaner bottom finish. None = use the same `step` for the last pass too. Negative just like `step`.
             */
            finish_step?: number | null;
            /**
             * Format: double
             * @description Corner radius for `FrameShape::RoundedRectangle`. None ⇒ defaults to `frame_padding_mm` inside the frame builder.
             */
            frame_corner_radius_mm?: number | null;
            /**
             * Format: double
             * @description Padding added on every side of the selection bbox to size the frame. Honored only when `frame_shape` is set.
             */
            frame_padding_mm?: number | null;
            /** @description Pocket-Outside wrapper: shape of the synthetic frame the pipeline auto-prepends around `source` before pocketing. Set only on ops created via the Pocket-Outside UX. None = no frame (regular Pocket). */
            frame_shape?: components["schemas"]["FrameShape"] | null;
            /**
             * @description Helical descent inside a closed contour.
             * @default false
             */
            helix: boolean;
            /**
             * @description Lead-in / lead-out shape for this op.
             * @default {
             *       "in": "off",
             *       "in_lenght": 5,
             *       "out": "off",
             *       "out_lenght": 5
             *     }
             */
            leads: components["schemas"]["LeadsConfig"];
            /**
             * @description V-Carve "second-pass" toggle. When true, the emitter runs a refinement pass that re-cuts only the points whose first pass fell short of the geometric target depth. Off by default.
             * @default false
             */
            multi_pass_refine: boolean;
            /**
             * @description Cut-order strategy for multiple objects.
             * @default nearest
             */
            objectorder: components["schemas"]["ObjectOrder"];
            /**
             * @description Dip into sharp inner corners so the cutter clears the geometric corner. Only meaningful for Profile ops with non-zero offset.
             * @default false
             */
            overcut: boolean;
            /** @description How the cutter descends into material at the start of each Z pass. Default Direct (straight plunge). Ramp { angle_deg } walks forward along the path while descending Z, taking a chip in both directions simultaneously — required for non-center-cutting bits and for harder materials. */
            plunge?: components["schemas"]["PlungeStrategy"];
            /**
             * Format: uint32
             * @description Override the tool's `plunge_rate` (Z feed) for this op. Useful for slowing the plunge on hard materials without changing the XY feed. Units: mm/min.
             */
            plunge_rate_override?: number | null;
            /** @default false */
            pocket_insideout: boolean;
            /** @default false */
            pocket_islands: boolean;
            /** @default false */
            pocket_nocontour: boolean;
            /**
             * @description Reverse the cut direction (climb ↔ conventional).
             * @default false
             */
            reverse: boolean;
            /**
             * Format: double
             * @description Z at which the first pass starts.
             */
            start_depth: number;
            /**
             * Format: double
             * @description Per-pass step (negative ⇒ down). None = inherit from `ToolEntry.default_step`. Legacy projects wrote a bare `0.0` to mean "unset"; the deserializer maps that to None.
             */
            step?: number | null;
            /**
             * @description Per-op tabs config. The Project's `tabs` map carries the actual placement points; this controls width / height / type.
             * @default {
             *       "active": false,
             *       "height": 1,
             *       "tab_type": "rectangle",
             *       "width": 10
             *     }
             */
            tabs: components["schemas"]["TabsConfig"];
            /**
             * Format: double
             * @description Cut past the nominal `depth` by this much (positive number — gets subtracted from the working depth). Useful for through-cuts on edge-clamped sheet so the cutter clears the bottom even with minor stock thickness variation. 0.0 = no extension.
             */
            through_depth?: number;
            /**
             * Format: double
             * @description XY overlap between consecutive pocket cuts, as a fraction in (0, 1). Drives the cascade step (= tool_diameter * (1 - overlap)) and the zigzag stride. 0.5 = 50% overlap = 50% stepover, a conservative default that fills tight pockets cleanly. Higher overlap = smaller step = more rings, slower cut, better finish. Lower overlap = bigger step = fewer rings, faster cut, may leave stripes. Honored only for Pocket ops; ignored elsewhere. Stored at 0.0 means "use the default" so old payloads still work.
             * @default 0
             */
            xy_overlap: number;
        };
        OperationSource: {
            combine?: components["schemas"]["SourceCombine"];
            /** @enum {string} */
            kind: "layers";
            layers: string[];
        } | {
            combine?: components["schemas"]["SourceCombine"];
            ids: number[];
            /** @enum {string} */
            kind: "objects";
        } | {
            /** @enum {string} */
            kind: "all";
        };
        /**
         * @description Pattern repetition for an [`Operation`]. When attached, the pipeline expands the op into N instances by translating (or rotating) the source geometry per instance — useful for "drill the same hole pattern N times" or "pocket N copies of the same shape on a grid".
         *
         *     The original geometry stays at the (0, 0) translation / 0° rotation instance so a single-instance pattern is identical to no pattern at all.
         */
        PatternConfig: {
            /** Format: uint32 */
            count: number;
            /** Format: double */
            dx: number;
            /** Format: double */
            dy: number;
            /** @enum {string} */
            kind: "linear";
        } | {
            /** Format: uint32 */
            count_x: number;
            /** Format: uint32 */
            count_y: number;
            /** Format: double */
            dx: number;
            /** Format: double */
            dy: number;
            /** @enum {string} */
            kind: "grid";
        } | {
            /** Format: double */
            angle_step_deg: number;
            /** Format: double */
            center_x: number;
            /** Format: double */
            center_y: number;
            /** Format: uint32 */
            count: number;
            /** @enum {string} */
            kind: "polar";
        };
        PipelineStats: {
            /** Format: uint */
            closed_object_count: number;
            /** Format: uint */
            object_count: number;
            /** Format: uint */
            offset_count: number;
        };
        /** @description One non-fatal warning attached to (optionally) a specific op. */
        PipelineWarning: {
            /** @description Stable identifier — frontend can branch on this to render an icon, link to docs, etc. */
            kind: string;
            /** @description Human-readable description. */
            message: string;
            /**
             * Format: uint32
             * @description Op the warning applies to. `None` means project-wide.
             */
            op_id?: number | null;
        };
        /** @description Per-pass entry strategy. */
        PlungeStrategy: {
            /** @enum {string} */
            kind: "direct";
        } | {
            /** Format: double */
            angle_deg: number;
            /** @enum {string} */
            kind: "ramp";
        } | {
            /** Format: double */
            angle_deg: number;
            /** @enum {string} */
            kind: "helix";
            /** Format: double */
            radius_mm?: number | null;
        };
        PocketConfig: {
            active: boolean;
            insideout: boolean;
            islands: boolean;
            /** @description Skip the boundary contour pass (used by HATCH-equivalent layers). */
            nocontour: boolean;
            zigzag: boolean;
        };
        PocketStrategy: ("cascade" | "zigzag" | "spiral") | {
            /** Format: double */
            engagement_angle_deg: number;
            /** @enum {string} */
            kind: "trochoidal";
            /** Format: double */
            loop_radius_factor: number;
        };
        Point2: {
            /** Format: double */
            x: number;
            /** Format: double */
            y: number;
        };
        /** @description One concentric offset of a closed object — used for both the boundary pass and any inward pocket cascade rings. */
        PolylineOffset: {
            closed: boolean;
            /** Format: int32 */
            color: number;
            /**
             * Format: uint8
             * @description 0 = boundary, 1 = zigzag fill stroke, 2 = pocket ring.
             */
            is_pocket: number;
            layer: string;
            /**
             * Format: uint32
             * @description 0 = outer boundary, 1+ = pocket cascade inward.
             */
            level: number;
            segments: components["schemas"]["Segment"][];
            /** Format: uint */
            source_object_idx: number;
            /** @description Tab positions (data-space XY) the cutter should lift over while cutting this offset. Frontend places these via mtm.10; the gcode emitter splits the cut at each crossing and lifts Z to tabs.height. */
            tabs?: components["schemas"]["TabPoint"][];
        };
        Pose3: {
            /** Format: double */
            x: number;
            /** Format: double */
            y: number;
            /** Format: double */
            z: number;
        };
        /** @enum {string} */
        PostProcessorKind: "linuxcnc" | "grbl" | "hpgl";
        Project: {
            machine: components["schemas"]["MachineConfig"];
            operations: components["schemas"]["Operation"][];
            /** @description Imported geometry — the same `segments` the existing pipeline consumes. We keep it inline rather than referencing it by id so the project file is self-contained. */
            segments: components["schemas"]["Segment"][];
            /** @description Tab placements keyed by imported-segment index. Same shape as the legacy PipelineRequest.tabs. */
            tabs?: {
                [key: string]: components["schemas"]["TabPoint"][];
            };
            tools: components["schemas"]["ToolEntry"][];
        };
        /** @description One filled region attached to a specific operation. `outer` is the outer boundary; `holes` are the islands the cutter must avoid. Both in project units (typically mm). */
        RegionPreview: {
            holes?: components["schemas"]["Point2"][][];
            /** Format: uint32 */
            op_id: number;
            outer: components["schemas"]["Point2"][];
        };
        /** @description Request payload for the cross-transport `/text` endpoint. The frontend hands us TTF bytes (uploaded by the user or pulled from `frontend/public/fonts/`) plus a string + placement parameters; we return flattened [`Segment`]s and a single-line / outline classification the dialog uses to drive the engraving warning chip. */
        RenderTextRequest: {
            /**
             * Format: int32
             * @default 7
             */
            color: number;
            /** @description The font file as bytes (TTF / OTF). Encoded as a JSON `Vec<u8>` (i.e. an array of byte values) so the contract works equally well over HTTP/Tauri/WASM without picking a base64 layer. */
            font_bytes: number[];
            /** Format: double */
            height_mm: number;
            /** @default TEXT */
            layer: string;
            origin: components["schemas"]["Point2"];
            text: string;
        };
        /** @description Response payload — the rendered geometry plus metadata the dialog uses to warn the user when an outline font is paired with the Engraving style. */
        RenderTextResponse: {
            /** @description Family / style names (best-effort). Useful for showing what the user actually loaded next to the dropdown. */
            family_name?: string | null;
            segments: components["schemas"]["Segment"][];
            /** @description True if the font is a single-line / engraving / Hershey-port style font. Drives the dialog's "use a single-line font" chip. */
            single_line: boolean;
        };
        /** @description A flat LINE/ARC primitive. ARC geometry is encoded as the bulge between `start` and `end` (bulge = `tan(included_angle / 4)`). */
        Segment: {
            /**
             * Format: double
             * @default 0
             */
            bulge: number;
            center?: components["schemas"]["Point2"] | null;
            /**
             * Format: int32
             * @default 7
             */
            color: number;
            end: components["schemas"]["Point2"];
            /** @default 0 */
            layer: string;
            start: components["schemas"]["Point2"];
            type: components["schemas"]["SegmentKind"];
        };
        /** @enum {string} */
        SegmentKind: "LINE" | "ARC" | "CIRCLE" | "POINT";
        Setup: {
            leads: components["schemas"]["LeadsConfig"];
            machine: components["schemas"]["MachineConfig"];
            mill: components["schemas"]["MillConfig"];
            pockets: components["schemas"]["PocketConfig"];
            tabs: components["schemas"]["TabsConfig"];
            tool: components["schemas"]["ToolConfig"];
        };
        /** @description How a multi-object source selection is combined into the region(s) the operation actually consumes. Default is `Auto` — containment-based, which gives the user "outer + inner = annulus" behavior with no extra thought. The other modes are clipper2-driven boolean ops; `None` keeps each selected object as its own boundary (the pre-combine behavior, surfaced for callers who really want it). */
        SourceCombine: "auto" | "union" | "difference" | "intersection" | "xor" | "none";
        TabPoint: {
            /** Format: double */
            x: number;
            /** Format: double */
            y: number;
        };
        /** @enum {string} */
        TabType: "rectangle" | "ramp";
        TabsConfig: {
            active: boolean;
            /**
             * Format: double
             * @description Z height the cutter lifts to over a tab (positive distance above the cut floor). The actual tab Z is `mill.depth + tabs.height`.
             */
            height: number;
            /**
             * Format: double
             * @description Ramp angle in degrees, used only when `tab_type == Ramp`. The horizontal length of each ramp into / out of a tab is `tabs.height / tan(ramp_angle_deg)`. 30° gives a 1:√3 slope. Ignored for Rectangle tabs.
             */
            ramp_angle_deg?: number;
            tab_type: components["schemas"]["TabType"];
            /** Format: double */
            width: number;
        };
        ToolConfig: {
            /** Format: double */
            diameter: number;
            /**
             * Format: double
             * @description Drag-knife offset (if present, otherwise None).
             */
            dragoff?: number | null;
            flood: boolean;
            mist: boolean;
            /** Format: uint32 */
            number: number;
            /**
             * Format: uint32
             * @description Spindle warm-up pause in seconds.
             */
            pause: number;
            /**
             * Format: uint32
             * @description Cutting feedrate (mm/min).
             */
            rate_h: number;
            /**
             * Format: uint32
             * @description Plunge feedrate (mm/min).
             */
            rate_v: number;
            /** Format: uint32 */
            speed: number;
        };
        ToolEntry: {
            coolant: components["schemas"]["Coolant"];
            /**
             * Format: double
             * @description Default depth-per-pass (negative, mm). Operations using this tool inherit this when their own `step` is unset. None = no default.
             */
            default_step?: number | null;
            /** Format: double */
            diameter: number;
            /**
             * Format: double
             * @description Drag-knife trailing offset (None for everything else).
             */
            dragoff?: number | null;
            /**
             * Format: uint32
             * @description Cutting feedrate (mm/min).
             */
            feed_rate: number;
            /** Format: uint8 */
            flutes: number;
            /** Format: uint32 */
            id: number;
            kind: components["schemas"]["ToolKind"];
            name: string;
            /**
             * Format: uint32
             * @description Plunge feedrate (mm/min).
             */
            plunge_rate: number;
            /** Format: uint32 */
            speed: number;
            /**
             * Format: double
             * @description V-bit full included tip angle in degrees (apex angle of the cone). Drives the V-Carve depth-from-width relationship `z = -R / tan(tip_angle / 2)`. Validated to (0, 180); defaults to 60° for the most common engraving V-bit.
             * @default 60
             */
            tip_angle_deg: number;
            /**
             * Format: double
             * @description V-bit tip diameter (None for endmill / ball nose / drag knife).
             */
            tip_diameter?: number | null;
        };
        ToolKind: ("endmill" | "ball_nose" | "v_bit" | "engraver" | "drag_knife" | "drill") | "laser_beam";
        /** @enum {string} */
        ToolOffset: "none" | "outside" | "inside" | "on";
        ToolpathSegment: {
            from: components["schemas"]["Pose3"];
            /**
             * Format: uint32
             * @description 1-based line number in the source gcode that produced this move. 0 means "synthetic / unknown".
             * @default 0
             */
            gcode_line: number;
            kind: components["schemas"]["MoveKind"];
            /**
             * Format: uint32
             * @description Operation id from the per-op emitter. 0 = legacy / unstamped.
             * @default 0
             */
            op_id: number;
            to: components["schemas"]["Pose3"];
        };
        /** @enum {string} */
        TransportKind: "python-bridge" | "rust-server" | "tauri" | "wasm";
        /** @enum {string} */
        UnitSystem: "mm" | "inch";
        /** @description `VcObject` analogue: a chain of segments grouped after `segments2objects`. */
        VcObject: {
            closed: boolean;
            /** Format: int32 */
            color: number;
            /** @description IDs of objects fully contained by this one. */
            inner_objects: number[];
            layer: string;
            /** @description IDs of objects fully containing this one. */
            outer_objects: number[];
            /**
             * Format: double
             * @description Per-object override of the tool-radius offset (None ⇒ tool diameter / 2).
             */
            overwrite_offset?: number | null;
            segments: components["schemas"]["Segment"][];
            /** @description Per-object setup overrides (mill depth, leads, tabs, …). */
            setup: components["schemas"]["Setup"];
            /** @description Optional starting point for cut-order seeding. */
            start?: components["schemas"]["Point2"] | null;
            /** @description "outside" / "inside" / "none" — see `setup::ToolOffset`. */
            tool_offset: components["schemas"]["ToolOffset"];
        };
        VersionResponse: {
            capabilities: string[];
            transport: components["schemas"]["TransportKind"];
            version: string;
        };
    };
    responses: {
        /** @description Malformed input */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Could not parse content */
        UnprocessableEntity: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service is up */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    version: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VersionResponse"];
                };
            };
        };
    };
    import: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    file: string;
                    /** @description Optional explicit format hint (dxf|svg|hpgl|ngc|stl). Inferred from filename otherwise. */
                    format?: string;
                };
            };
        };
        responses: {
            /** @description Parsed geometry */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            422: components["responses"]["UnprocessableEntity"];
        };
    };
    generate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GenerateRequest"];
            };
        };
        responses: {
            /** @description Generated output */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenerateResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    renderText: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RenderTextRequest"];
            };
        };
        responses: {
            /** @description Rendered text geometry */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RenderTextResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
}
