//! GRBL post-processor. Mostly identical to `LinuxCNC`; differences:
//! - No G64 path-blending pragma
//! - Tool change is omitted (GRBL is single-tool)
//! - Coolant mist (M7) often unsupported; we still emit it for symmetry.

// # CAM/sim pedantic-lint exemptions
// GRBL post emits the same gcode-letter short names as the LinuxCNC post
// (X/Y/Z/I/J/F/S).
#![allow(
    clippy::many_single_char_names,
)]


use crate::cam::setup::{ToolOffset, UnitSystem};
use crate::gcode::{linuxcnc, CapturedPostState, PostProcessor};

#[derive(Debug, Default)]
pub struct Post {
    inner: linuxcnc::Post,
}

impl Post {
    #[must_use] pub fn new() -> Self {
        Self::default()
    }
}

impl PostProcessor for Post {
    fn separation(&mut self) {
        self.inner.separation();
    }
    fn raw(&mut self, cmd: &str) {
        self.inner.raw(cmd);
    }
    fn comment(&mut self, text: &str) {
        // GRBL strips parentheses-wrapped comments; emit as semicolon for safety.
        self.inner.raw(&format!("; {text}"));
    }
    fn unit(&mut self, unit: UnitSystem) {
        self.inner.unit(unit);
    }
    fn absolute(&mut self, active: bool) {
        self.inner.absolute(active);
    }
    fn feedrate(&mut self, rate: u32) {
        self.inner.feedrate(rate);
    }
    fn program_start(&mut self) {
        // Delegate to LinuxCNC's program_start so the user-configured
        // profile (rt1.15) drives the header. The default fallback
        // inside linuxcnc emits `(generated by wiaConstructor)`,
        // which is wrong for GRBL (GRBL strips paren comments). We
        // ALWAYS provide a GRBL-friendly default via the inner raw()
        // call when no profile is set.
        if self.inner.state.profile.is_some() {
            self.inner.program_start();
        } else {
            self.inner.raw("; generated by wiaConstructor (GRBL)");
        }
    }
    fn program_end(&mut self) {
        if self.inner.state.profile.is_some() {
            self.inner.program_end();
        } else {
            self.inner.raw("M2");
        }
    }
    fn tool(&mut self, n: u32) {
        // GRBL is single-tool by default; emit nothing UNLESS the
        // user-configured profile has a tool_change template — they
        // may run modified GRBL with toolchange macros.
        if self.inner.state.profile.is_some() {
            self.inner.tool(n);
        }
    }
    fn tool_offsets(&mut self, offset: ToolOffset) {
        self.inner.tool_offsets(offset);
    }
    fn machine_offsets(&mut self, offsets: (f64, f64, f64), soft: bool) {
        self.inner.machine_offsets(offsets, soft);
    }
    fn coolant_mist(&mut self) {
        self.inner.coolant_mist();
    }
    fn coolant_flood(&mut self) {
        self.inner.coolant_flood();
    }
    fn coolant_off(&mut self) {
        self.inner.coolant_off();
    }
    fn spindle_off(&mut self) {
        self.inner.spindle_off();
    }
    fn spindle_cw(&mut self, speed: u32, pause: u32) {
        self.inner.spindle_cw(speed, pause);
    }
    fn spindle_ccw(&mut self, speed: u32, pause: u32) {
        self.inner.spindle_ccw(speed, pause);
    }
    fn move_to(&mut self, x: Option<f64>, y: Option<f64>, z: Option<f64>) {
        self.inner.move_to(x, y, z);
    }
    fn linear(&mut self, x: Option<f64>, y: Option<f64>, z: Option<f64>) {
        self.inner.linear(x, y, z);
    }
    fn arc_cw(
        &mut self,
        x: Option<f64>,
        y: Option<f64>,
        z: Option<f64>,
        i: Option<f64>,
        j: Option<f64>,
    ) {
        self.inner.arc_cw(x, y, z, i, j);
    }
    fn arc_ccw(
        &mut self,
        x: Option<f64>,
        y: Option<f64>,
        z: Option<f64>,
        i: Option<f64>,
        j: Option<f64>,
    ) {
        self.inner.arc_ccw(x, y, z, i, j);
    }
    fn finish(&self) -> String {
        self.inner.finish()
    }
    fn out_lines_count(&self) -> usize {
        self.inner.out_lines_count()
    }
    fn out_lines_clone_from(&self, start: usize) -> Vec<String> {
        self.inner.out_lines_clone_from(start)
    }
    fn out_extend_lines(&mut self, lines: &[String]) {
        self.inner.out_extend_lines(lines);
    }
    fn reset_state(&mut self) {
        self.inner.reset_state();
    }
    fn capture_state(&self) -> CapturedPostState {
        self.inner.capture_state()
    }
    fn restore_state(&mut self, s: &CapturedPostState) {
        self.inner.restore_state(s);
    }
    fn configure(&mut self, decimal_separator: char, line_number_start: Option<u32>) {
        self.inner.configure(decimal_separator, line_number_start);
    }
    fn tool_z_shift(&mut self, shift_mm: f64) {
        // GRBL accepts G92 albeit with caveats (some firmware revisions
        // ignore Z component). Emit it through the inner LinuxCNC post
        // so the output line is identical; controllers that ignore G92
        // simply skip it.
        self.inner.tool_z_shift(shift_mm);
    }
    fn dwell(&mut self, seconds: f64) {
        self.inner.dwell(seconds);
    }
    fn set_post_profile(&mut self, profile: Option<&crate::gcode::post_profile::PostProfile>) {
        self.inner.set_post_profile(profile);
    }
    fn set_token_ctx(&mut self, ctx: &crate::gcode::post_profile::TokenCtx) {
        self.inner.set_token_ctx(ctx);
    }
}
