//! GRBL post-processor. Mostly identical to LinuxCNC; differences:
//! - No G64 path-blending pragma
//! - Tool change is omitted (GRBL is single-tool)
//! - Coolant mist (M7) often unsupported; we still emit it for symmetry.

use crate::cam::setup::{ToolOffset, UnitSystem};
use crate::gcode::{linuxcnc, PostProcessor};

#[derive(Debug, Default)]
pub struct Post {
    inner: linuxcnc::Post,
}

impl Post {
    pub fn new() -> Self {
        Self::default()
    }
}

impl PostProcessor for Post {
    fn separation(&mut self) {
        self.inner.separation();
    }
    fn raw(&mut self, cmd: &str) {
        self.inner.raw(cmd);
    }
    fn comment(&mut self, text: &str) {
        // GRBL strips parentheses-wrapped comments; emit as semicolon for safety.
        self.inner.raw(&format!("; {text}"));
    }
    fn unit(&mut self, unit: UnitSystem) {
        self.inner.unit(unit);
    }
    fn absolute(&mut self, active: bool) {
        self.inner.absolute(active);
    }
    fn feedrate(&mut self, rate: u32) {
        self.inner.feedrate(rate);
    }
    fn program_start(&mut self) {
        self.inner.raw("; generated by wiaConstructor (GRBL)");
    }
    fn program_end(&mut self) {
        self.inner.raw("M2");
    }
    fn tool(&mut self, _number: u32) {
        // GRBL is single-tool; ignore.
    }
    fn tool_offsets(&mut self, offset: ToolOffset) {
        self.inner.tool_offsets(offset);
    }
    fn machine_offsets(&mut self, offsets: (f64, f64, f64), soft: bool) {
        self.inner.machine_offsets(offsets, soft);
    }
    fn coolant_mist(&mut self) {
        self.inner.coolant_mist();
    }
    fn coolant_flood(&mut self) {
        self.inner.coolant_flood();
    }
    fn coolant_off(&mut self) {
        self.inner.coolant_off();
    }
    fn spindle_off(&mut self) {
        self.inner.spindle_off();
    }
    fn spindle_cw(&mut self, speed: u32, pause: u32) {
        self.inner.spindle_cw(speed, pause);
    }
    fn spindle_ccw(&mut self, speed: u32, pause: u32) {
        self.inner.spindle_ccw(speed, pause);
    }
    fn move_to(&mut self, x: Option<f64>, y: Option<f64>, z: Option<f64>) {
        self.inner.move_to(x, y, z);
    }
    fn linear(&mut self, x: Option<f64>, y: Option<f64>, z: Option<f64>) {
        self.inner.linear(x, y, z);
    }
    fn arc_cw(
        &mut self,
        x: Option<f64>,
        y: Option<f64>,
        z: Option<f64>,
        i: Option<f64>,
        j: Option<f64>,
    ) {
        self.inner.arc_cw(x, y, z, i, j);
    }
    fn arc_ccw(
        &mut self,
        x: Option<f64>,
        y: Option<f64>,
        z: Option<f64>,
        i: Option<f64>,
        j: Option<f64>,
    ) {
        self.inner.arc_ccw(x, y, z, i, j);
    }
    fn finish(&self) -> String {
        self.inner.finish()
    }
}
