//! LinuxCNC post-processor. Mirrors output_plugins/gcode_linuxcnc.py.

use crate::cam::setup::{ToolOffset, UnitSystem};
use crate::gcode::post_profile::{template_lines, PostProfile, TokenCtx};
use crate::gcode::{
    configure_post_state, fmt_num, line_number_prefix, CapturedPostState, PostProcessor, PostState,
};

#[derive(Debug, Default)]
pub struct Post {
    /// Internal state — exposed `pub(crate)` so the GRBL post can
    /// check `state.profile` to decide whether to delegate to
    /// LinuxCNC's template-driven program_start / _end / tool path.
    pub(crate) state: PostState,
    out: Vec<String>,
}

impl Post {
    pub fn new() -> Self {
        Self::default()
    }

    fn write(&mut self, line: impl Into<String>) {
        let raw: String = line.into();
        let prefix = line_number_prefix(&mut self.state);
        if prefix.is_empty() {
            self.out.push(raw);
        } else {
            self.out.push(format!("{prefix}{raw}"));
        }
    }

    fn fmt(&self, v: f64) -> String {
        fmt_num(v, self.state.decimal_separator)
    }

    fn maybe(&self, coord: char, prev: Option<f64>, val: Option<f64>) -> Option<String> {
        let v = val?;
        if let Some(p) = prev {
            if (p - v).abs() < 1e-9 {
                return None;
            }
        }
        Some(format!("{coord}{}", self.fmt(v)))
    }

    fn coords(&mut self, x: Option<f64>, y: Option<f64>, z: Option<f64>) -> String {
        let last_x = self.state.last_x;
        let last_y = self.state.last_y;
        let last_z = self.state.last_z;
        let mut parts = Vec::with_capacity(3);
        if let Some(s) = self.maybe('X', last_x, x) {
            parts.push(s);
        }
        if let Some(s) = self.maybe('Y', last_y, y) {
            parts.push(s);
        }
        if let Some(s) = self.maybe('Z', last_z, z) {
            parts.push(s);
        }
        if let Some(v) = x {
            self.state.last_x = Some(v);
        }
        if let Some(v) = y {
            self.state.last_y = Some(v);
        }
        if let Some(v) = z {
            self.state.last_z = Some(v);
        }
        parts.join(" ")
    }
}


impl PostProcessor for Post {
    fn separation(&mut self) {
        self.write("");
    }
    fn raw(&mut self, cmd: &str) {
        self.write(cmd);
    }
    fn comment(&mut self, text: &str) {
        self.write(format!("({text})"));
    }
    fn unit(&mut self, unit: UnitSystem) {
        self.write(match unit {
            UnitSystem::Mm => "G21",
            UnitSystem::Inch => "G20",
        });
    }
    fn absolute(&mut self, active: bool) {
        if active {
            self.state.absolute = true;
            self.write("G90");
        } else {
            self.state.absolute = false;
            self.write("G91");
        }
    }
    fn feedrate(&mut self, rate: u32) {
        if self.state.last_rate != Some(rate) {
            self.write(format!("F{rate}"));
            self.state.last_rate = Some(rate);
        }
    }
    fn program_start(&mut self) {
        if let Some(template) = self.state.profile.as_ref().and_then(|p| p.program_start.clone()) {
            for line in template_lines(&template, &self.state.token_ctx) {
                self.write(line);
            }
        } else {
            self.write("(generated by wiaConstructor)");
        }
    }
    fn program_end(&mut self) {
        if let Some(template) = self.state.profile.as_ref().and_then(|p| p.program_end.clone()) {
            for line in template_lines(&template, &self.state.token_ctx) {
                self.write(line);
            }
        } else {
            self.write("M30");
        }
    }
    fn tool(&mut self, n: u32) {
        // Refresh tool-number token before rendering so the template
        // sees the FUTURE tool's number even mid-program.
        self.state.token_ctx.tool_number = n;
        if let Some(template) = self.state.profile.as_ref().and_then(|p| p.tool_change.clone()) {
            for line in template_lines(&template, &self.state.token_ctx) {
                self.write(line);
            }
        } else {
            self.write(format!("T{n} M6"));
        }
    }
    fn tool_offsets(&mut self, offset: ToolOffset) {
        match offset {
            ToolOffset::None => self.write("G40"),
            ToolOffset::Inside => self.write("G42"),
            ToolOffset::Outside => self.write("G41"),
            ToolOffset::On => self.write("G40"),
        }
    }
    fn machine_offsets(&mut self, offsets: (f64, f64, f64), _soft: bool) {
        self.write(format!(
            "G92 X{} Y{} Z{}",
            self.fmt(offsets.0),
            self.fmt(offsets.1),
            self.fmt(offsets.2)
        ));
    }
    fn coolant_mist(&mut self) {
        if let Some(template) = self
            .state
            .profile
            .as_ref()
            .and_then(|p| p.coolant_mist_on.clone())
        {
            for line in template_lines(&template, &self.state.token_ctx) {
                self.write(line);
            }
        } else {
            self.write("M7");
        }
    }
    fn coolant_flood(&mut self) {
        if let Some(template) = self
            .state
            .profile
            .as_ref()
            .and_then(|p| p.coolant_flood_on.clone())
        {
            for line in template_lines(&template, &self.state.token_ctx) {
                self.write(line);
            }
        } else {
            self.write("M8");
        }
    }
    fn coolant_off(&mut self) {
        // Pick the off template based on which coolant variant we
        // think is still on (state.last_speed is unreliable here).
        // For v1: prefer flood-off if either is set, else mist-off.
        let off_template = self.state.profile.as_ref().and_then(|p| {
            p.coolant_flood_off
                .clone()
                .or_else(|| p.coolant_mist_off.clone())
        });
        if let Some(template) = off_template {
            for line in template_lines(&template, &self.state.token_ctx) {
                self.write(line);
            }
        } else {
            self.write("M9");
        }
    }
    fn spindle_off(&mut self) {
        self.write("M5");
        self.state.last_speed = None;
    }
    fn spindle_cw(&mut self, speed: u32, pause: u32) {
        if self.state.last_speed != Some(speed) {
            self.write(format!("M3 S{speed}"));
            self.state.last_speed = Some(speed);
            if pause > 0 {
                self.write(format!("G4 P{pause}"));
            }
        }
    }
    fn spindle_ccw(&mut self, speed: u32, pause: u32) {
        if self.state.last_speed != Some(speed) {
            self.write(format!("M4 S{speed}"));
            self.state.last_speed = Some(speed);
            if pause > 0 {
                self.write(format!("G4 P{pause}"));
            }
        }
    }
    fn move_to(&mut self, x: Option<f64>, y: Option<f64>, z: Option<f64>) {
        let body = self.coords(x, y, z);
        if !body.is_empty() {
            self.write(format!("G0 {body}"));
        }
    }
    fn linear(&mut self, x: Option<f64>, y: Option<f64>, z: Option<f64>) {
        let body = self.coords(x, y, z);
        if !body.is_empty() {
            self.write(format!("G1 {body}"));
        }
    }
    fn arc_cw(
        &mut self,
        x: Option<f64>,
        y: Option<f64>,
        z: Option<f64>,
        i: Option<f64>,
        j: Option<f64>,
    ) {
        let body = self.coords(x, y, z);
        let i = i.map(|v| format!(" I{}", self.fmt(v))).unwrap_or_default();
        let j = j.map(|v| format!(" J{}", self.fmt(v))).unwrap_or_default();
        self.write(format!("G2 {body}{i}{j}").trim().to_string());
    }
    fn arc_ccw(
        &mut self,
        x: Option<f64>,
        y: Option<f64>,
        z: Option<f64>,
        i: Option<f64>,
        j: Option<f64>,
    ) {
        let body = self.coords(x, y, z);
        let i = i.map(|v| format!(" I{}", self.fmt(v))).unwrap_or_default();
        let j = j.map(|v| format!(" J{}", self.fmt(v))).unwrap_or_default();
        self.write(format!("G3 {body}{i}{j}").trim().to_string());
    }
    fn drill_simple(&mut self, x: f64, y: f64, z: f64, r: f64, dwell_sec: f64) {
        // LinuxCNC G81 / G82 (G82 is the dwell variant). Use G82 when dwell > 0,
        // G81 otherwise, so machinists who watch the canned cycle code see what
        // they expect.
        let dwell = if dwell_sec > 0.0 {
            format!(" P{}", self.fmt(dwell_sec))
        } else {
            String::new()
        };
        let g = if dwell_sec > 0.0 { "G82" } else { "G81" };
        let body = self.coords(Some(x), Some(y), Some(z));
        self.write(format!("{g} {body} R{}{dwell}", self.fmt(r)));
        // Canned cycles leave Z at R after each cycle, but the post state
        // already records Z=z above. Sync it so subsequent moves don't
        // emit redundant Z words.
        self.state.last_z = Some(r);
    }
    fn drill_peck(&mut self, x: f64, y: f64, z: f64, r: f64, q: f64, dwell_sec: f64) {
        let dwell = if dwell_sec > 0.0 {
            format!(" P{}", self.fmt(dwell_sec))
        } else {
            String::new()
        };
        let body = self.coords(Some(x), Some(y), Some(z));
        self.write(format!(
            "G83 {body} R{} Q{}{dwell}",
            self.fmt(r),
            self.fmt(q.abs())
        ));
        self.state.last_z = Some(r);
    }
    fn drill_chip_break(&mut self, x: f64, y: f64, z: f64, r: f64, q: f64, dwell_sec: f64) {
        let dwell = if dwell_sec > 0.0 {
            format!(" P{}", self.fmt(dwell_sec))
        } else {
            String::new()
        };
        let body = self.coords(Some(x), Some(y), Some(z));
        self.write(format!(
            "G73 {body} R{} Q{}{dwell}",
            self.fmt(r),
            self.fmt(q.abs())
        ));
        self.state.last_z = Some(r);
    }
    fn finish(&self) -> String {
        self.out.join("\n") + "\n"
    }
    fn out_lines_count(&self) -> usize {
        self.out.len()
    }
    fn out_lines_clone_from(&self, start: usize) -> Vec<String> {
        if start >= self.out.len() {
            Vec::new()
        } else {
            self.out[start..].to_vec()
        }
    }
    fn out_extend_lines(&mut self, lines: &[String]) {
        self.out.extend_from_slice(lines);
    }
    fn reset_state(&mut self) {
        self.state.last_x = None;
        self.state.last_y = None;
        self.state.last_z = None;
        self.state.last_rate = None;
        self.state.last_speed = None;
    }
    fn capture_state(&self) -> CapturedPostState {
        CapturedPostState {
            last_x: self.state.last_x,
            last_y: self.state.last_y,
            last_z: self.state.last_z,
            last_rate: self.state.last_rate,
            last_speed: self.state.last_speed,
        }
    }
    fn restore_state(&mut self, s: &CapturedPostState) {
        self.state.last_x = s.last_x;
        self.state.last_y = s.last_y;
        self.state.last_z = s.last_z;
        self.state.last_rate = s.last_rate;
        self.state.last_speed = s.last_speed;
    }
    fn configure(&mut self, decimal_separator: char, line_number_start: Option<u32>) {
        configure_post_state(&mut self.state, decimal_separator, line_number_start);
    }
    fn tool_z_shift(&mut self, shift_mm: f64) {
        if shift_mm.abs() < 1e-9 {
            return;
        }
        // G92 sets the work-coordinate offset; here we pin the work Z
        // to the configured shift so the new tool's tip lines up with
        // the reference tool's Z=0. The `;` comment is bracketed so
        // grep'ing for the offset is easy in CAM-review.
        let s = self.fmt(shift_mm);
        self.write(format!("(z-shift: {s})"));
        self.write(format!("G92 Z{s}"));
        // The G92 leaves the controller's internal "last_z" unknown
        // to our delta encoder — flushing it forces the next Z move
        // to re-emit explicitly.
        self.state.last_z = None;
    }
    fn dwell(&mut self, seconds: f64) {
        if seconds <= 0.0 {
            return;
        }
        let s = self.fmt(seconds);
        self.write(format!("G4 P{s}"));
    }
    fn set_post_profile(&mut self, profile: Option<&PostProfile>) {
        self.state.profile = profile.cloned();
    }
    fn set_token_ctx(&mut self, ctx: &TokenCtx) {
        self.state.token_ctx = ctx.clone();
    }
}
