//! LinuxCNC post-processor. Mirrors output_plugins/gcode_linuxcnc.py.

use crate::cam::setup::{ToolOffset, UnitSystem};
use crate::gcode::{PostProcessor, PostState};

#[derive(Debug, Default)]
pub struct Post {
    state: PostState,
    out: Vec<String>,
}

impl Post {
    pub fn new() -> Self {
        Self::default()
    }

    fn write(&mut self, line: impl Into<String>) {
        self.out.push(line.into());
    }
}

fn fmt(v: f64) -> String {
    // Match the upstream's formatting: 4 decimal places, strip trailing zeros.
    let s = format!("{v:.4}");
    let trimmed = s.trim_end_matches('0').trim_end_matches('.');
    if trimmed.is_empty() {
        "0".into()
    } else {
        trimmed.to_string()
    }
}

fn maybe(coord: char, prev: Option<f64>, val: Option<f64>) -> Option<String> {
    let v = val?;
    if let Some(p) = prev {
        if (p - v).abs() < 1e-9 {
            return None;
        }
    }
    Some(format!("{coord}{}", fmt(v)))
}

fn coords(
    state: &mut PostState,
    x: Option<f64>,
    y: Option<f64>,
    z: Option<f64>,
) -> String {
    let mut parts = Vec::with_capacity(3);
    if let Some(s) = maybe('X', state.last_x, x) {
        parts.push(s);
    }
    if let Some(s) = maybe('Y', state.last_y, y) {
        parts.push(s);
    }
    if let Some(s) = maybe('Z', state.last_z, z) {
        parts.push(s);
    }
    if let Some(v) = x {
        state.last_x = Some(v);
    }
    if let Some(v) = y {
        state.last_y = Some(v);
    }
    if let Some(v) = z {
        state.last_z = Some(v);
    }
    parts.join(" ")
}

impl PostProcessor for Post {
    fn separation(&mut self) {
        self.write("");
    }
    fn raw(&mut self, cmd: &str) {
        self.write(cmd);
    }
    fn comment(&mut self, text: &str) {
        self.write(format!("({text})"));
    }
    fn unit(&mut self, unit: UnitSystem) {
        self.write(match unit {
            UnitSystem::Mm => "G21",
            UnitSystem::Inch => "G20",
        });
    }
    fn absolute(&mut self, active: bool) {
        if active {
            self.state.absolute = true;
            self.write("G90");
        } else {
            self.state.absolute = false;
            self.write("G91");
        }
    }
    fn feedrate(&mut self, rate: u32) {
        if self.state.last_rate != Some(rate) {
            self.write(format!("F{rate}"));
            self.state.last_rate = Some(rate);
        }
    }
    fn program_start(&mut self) {
        self.write("(generated by wiaConstructor)");
    }
    fn program_end(&mut self) {
        self.write("M30");
    }
    fn tool(&mut self, n: u32) {
        self.write(format!("T{n} M6"));
    }
    fn tool_offsets(&mut self, offset: ToolOffset) {
        match offset {
            ToolOffset::None => self.write("G40"),
            ToolOffset::Inside => self.write("G42"),
            ToolOffset::Outside => self.write("G41"),
            ToolOffset::On => self.write("G40"),
        }
    }
    fn machine_offsets(&mut self, offsets: (f64, f64, f64), _soft: bool) {
        self.write(format!(
            "G92 X{} Y{} Z{}",
            fmt(offsets.0),
            fmt(offsets.1),
            fmt(offsets.2)
        ));
    }
    fn coolant_mist(&mut self) {
        self.write("M7");
    }
    fn coolant_flood(&mut self) {
        self.write("M8");
    }
    fn coolant_off(&mut self) {
        self.write("M9");
    }
    fn spindle_off(&mut self) {
        self.write("M5");
        self.state.last_speed = None;
    }
    fn spindle_cw(&mut self, speed: u32, pause: u32) {
        if self.state.last_speed != Some(speed) {
            self.write(format!("M3 S{speed}"));
            self.state.last_speed = Some(speed);
            if pause > 0 {
                self.write(format!("G4 P{pause}"));
            }
        }
    }
    fn spindle_ccw(&mut self, speed: u32, pause: u32) {
        if self.state.last_speed != Some(speed) {
            self.write(format!("M4 S{speed}"));
            self.state.last_speed = Some(speed);
            if pause > 0 {
                self.write(format!("G4 P{pause}"));
            }
        }
    }
    fn move_to(&mut self, x: Option<f64>, y: Option<f64>, z: Option<f64>) {
        let body = coords(&mut self.state, x, y, z);
        if !body.is_empty() {
            self.write(format!("G0 {body}"));
        }
    }
    fn linear(&mut self, x: Option<f64>, y: Option<f64>, z: Option<f64>) {
        let body = coords(&mut self.state, x, y, z);
        if !body.is_empty() {
            self.write(format!("G1 {body}"));
        }
    }
    fn arc_cw(
        &mut self,
        x: Option<f64>,
        y: Option<f64>,
        z: Option<f64>,
        i: Option<f64>,
        j: Option<f64>,
    ) {
        let body = coords(&mut self.state, x, y, z);
        let i = i.map(|v| format!(" I{}", fmt(v))).unwrap_or_default();
        let j = j.map(|v| format!(" J{}", fmt(v))).unwrap_or_default();
        self.write(format!("G2 {body}{i}{j}").trim().to_string());
    }
    fn arc_ccw(
        &mut self,
        x: Option<f64>,
        y: Option<f64>,
        z: Option<f64>,
        i: Option<f64>,
        j: Option<f64>,
    ) {
        let body = coords(&mut self.state, x, y, z);
        let i = i.map(|v| format!(" I{}", fmt(v))).unwrap_or_default();
        let j = j.map(|v| format!(" J{}", fmt(v))).unwrap_or_default();
        self.write(format!("G3 {body}{i}{j}").trim().to_string());
    }
    fn finish(&self) -> String {
        self.out.join("\n") + "\n"
    }
}
