//! User-configurable post-processor profile (rt1.15, hev).
//!
//! A `PostProfile` is a serde-friendly bundle of TEMPLATE STRINGS that
//! override the hard-coded headers / footers / toolchange / coolant
//! lines that the built-in `linuxcnc.rs` / `grbl.rs` emitters bake in.
//! Each template runs through [`substitute`] at emit time so the user
//! can reference the current tool / feed / spindle / op without
//! editing wiac source.
//!
//! v2 (hev) adds per-axis formatting: each of X/Y/Z/I/J/F/S can be
//! renamed (e.g. swap Z↔A for rotary), reformatted (`%.4f` for a
//! lathe), scaled (`-1` flips a Z-up controller, `1.0/60.0` converts
//! mm/min→mm/s), or disabled (skip the axis entirely, useful for
//! laser controllers that ignore Z).

use schemars::JsonSchema;
use serde::{Deserialize, Serialize};

use crate::cam::setup::UnitSystem;

/// A named bundle of override templates the user attaches to a
/// machine config. Any field left at `None` keeps the built-in
/// emitter's default behavior. The active variant of
/// `PostProcessorKind` is unaffected — wiac's linuxcnc / grbl / hpgl
/// emitters continue to drive line-level formatting (delta encoding,
/// arc fitting, drill cycles). The profile only swaps the
/// PROGRAM-LEVEL strings.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize, JsonSchema)]
pub struct PostProfile {
    /// User-facing label. Shown in MachineDialog's profile picker;
    /// not interpreted by the engine.
    #[serde(default)]
    pub name: String,
    /// File extension for save-to-disk (no leading dot). Default
    /// `"nc"`. Mach3 commonly uses `"tap"`, GRBL stays `"nc"`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub file_extension: Option<String>,
    /// Line separator on save. None ⇒ `"\n"`. Set to `"\r\n"` for
    /// FANUC / vintage Windows-y controllers.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub line_ending: Option<String>,
    /// PROGRAM_START template. Replaces the `(generated by …)`
    /// header line. Can contain multiple `\n`-separated lines via
    /// the `<NL>` token.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub program_start: Option<String>,
    /// PROGRAM_END template. Replaces the `M30` footer line.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub program_end: Option<String>,
    /// TOOL_CHANGE template. Replaces the `T<n> M6` toolchange line.
    /// Substitution context exposes the FUTURE tool's metadata.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub tool_change: Option<String>,
    /// COOLANT_FLOOD ON / OFF templates. Replace `M8` / `M9`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub coolant_flood_on: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub coolant_flood_off: Option<String>,
    /// COOLANT_MIST ON / OFF templates. Replace `M7` / `M9`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub coolant_mist_on: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub coolant_mist_off: Option<String>,
    /// Per-axis output format (hev). When set, replaces the hard-coded
    /// `X{val} Y{val} Z{val}` / `I{val} J{val}` / `F{rate}` / `S{rpm}`
    /// emission with the user's axis names + printf-ish format + scale,
    /// with per-axis enable so disabled axes drop out entirely.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub axes: Option<AxesConfig>,
}

/// Per-axis output configuration. `enabled=false` means "drop this
/// axis from the line entirely" (laser controllers commonly ignore Z;
/// some lathes ignore Y). `name` is the output letter — rename Z to
/// A for a rotary-as-Z setup. `format` is a tiny printf-ish spec.
/// `scale` is a multiplier applied BEFORE formatting (`-1.0` flips
/// the Z-up vs Z-down convention; `0.0393701` mm→inch).
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, JsonSchema)]
pub struct AxisFormat {
    #[serde(default = "default_true")]
    pub enabled: bool,
    pub name: String,
    pub format: String,
    pub scale: f64,
}

fn default_true() -> bool {
    true
}

impl AxisFormat {
    /// Default coordinate axis: enabled, named after the letter, three
    /// decimals, identity scale.
    #[must_use]
    pub fn coord(name: &str) -> Self {
        Self {
            enabled: true,
            name: name.into(),
            format: "%.3f".into(),
            scale: 1.0,
        }
    }

    /// Default integer axis (feed, spindle): enabled, named after the
    /// letter, integer format, identity scale.
    #[must_use]
    pub fn integer(name: &str) -> Self {
        Self {
            enabled: true,
            name: name.into(),
            format: "%d".into(),
            scale: 1.0,
        }
    }

    /// Render `value` (already in source units, e.g. mm or mm/min) as
    /// `<name><formatted_value>`. Returns `None` when this axis is
    /// disabled, so callers can use `?` to drop the word.
    #[must_use]
    pub fn render(&self, value: f64) -> Option<String> {
        if !self.enabled {
            return None;
        }
        Some(format!(
            "{}{}",
            self.name,
            format_axis_value(&self.format, value * self.scale)
        ))
    }
}

/// Bundle of per-axis output configs. Set on `PostProfile::axes` to
/// take over from the hard-coded axis letters / `%.3f` format in the
/// LinuxCNC / GRBL posts. All seven axes default to their natural
/// letter + sensible format, so `AxesConfig::default()` is the same
/// as the legacy hand-written behavior — the user only changes what
/// they care about.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, JsonSchema)]
pub struct AxesConfig {
    pub x: AxisFormat,
    pub y: AxisFormat,
    pub z: AxisFormat,
    pub i: AxisFormat,
    pub j: AxisFormat,
    pub feed: AxisFormat,
    pub speed: AxisFormat,
}

impl Default for AxesConfig {
    fn default() -> Self {
        Self {
            x: AxisFormat::coord("X"),
            y: AxisFormat::coord("Y"),
            z: AxisFormat::coord("Z"),
            i: AxisFormat::coord("I"),
            j: AxisFormat::coord("J"),
            feed: AxisFormat::integer("F"),
            speed: AxisFormat::integer("S"),
        }
    }
}

/// Tiny printf-ish formatter. Accepts a single conversion spec inside
/// an optional literal prefix/suffix:
///   `%[flags][width][.precision]<type>`
/// where flags ∈ `0 - +`, type ∈ `f g d i e`. Unrecognized type falls
/// back to `f`. Empty or `%`-less strings render as `%.3f`. The
/// caller is responsible for swapping `.` to a locale-specific
/// decimal separator after the fact.
#[must_use]
pub fn format_axis_value(format: &str, value: f64) -> String {
    if format.is_empty() {
        return format!("{value:.3}");
    }
    let bytes = format.as_bytes();
    let Some(pct) = bytes.iter().position(|&b| b == b'%') else {
        // No % anywhere — treat the whole string as a literal so a
        // misconfigured profile produces a visible eyesore rather
        // than silently dropping the value.
        return format.to_string();
    };

    let mut i = pct + 1;
    let mut zero_pad = false;
    let mut plus_sign = false;
    let mut left_align = false;
    while i < bytes.len() {
        match bytes[i] {
            b'0' => zero_pad = true,
            b'-' => left_align = true,
            b'+' => plus_sign = true,
            b' ' => {}
            _ => break,
        }
        i += 1;
    }

    let mut width: usize = 0;
    while i < bytes.len() && bytes[i].is_ascii_digit() {
        width = width * 10 + (bytes[i] - b'0') as usize;
        i += 1;
    }

    let mut precision: Option<usize> = None;
    if i < bytes.len() && bytes[i] == b'.' {
        i += 1;
        let pstart = i;
        while i < bytes.len() && bytes[i].is_ascii_digit() {
            i += 1;
        }
        if i > pstart {
            precision = std::str::from_utf8(&bytes[pstart..i])
                .ok()
                .and_then(|s| s.parse().ok());
        } else {
            precision = Some(0);
        }
    }

    let typ = bytes.get(i).copied().unwrap_or(b'f') as char;
    let after_type = if i < bytes.len() { i + 1 } else { i };

    let prefix = std::str::from_utf8(&bytes[..pct]).unwrap_or("");
    let suffix = std::str::from_utf8(&bytes[after_type..]).unwrap_or("");

    let prec = precision.unwrap_or(3);
    let mut body = match typ {
        'd' | 'i' => {
            #[allow(clippy::cast_possible_truncation)]
            let n = value.round() as i64;
            if plus_sign && n >= 0 {
                format!("+{n}")
            } else {
                n.to_string()
            }
        }
        'e' | 'E' => {
            let s = format!("{value:.prec$e}");
            if typ == 'E' {
                s.to_uppercase()
            } else {
                s
            }
        }
        'g' | 'G' => {
            // %g: trim trailing zeros after the decimal, drop dangling
            // '.', strip "+0" exponent suffixes from very small values
            // (`%g` would render those in scientific form on a real
            // libc, but our typical inputs stay in fixed range).
            let raw = format!("{value:.prec$}");
            if let Some(stripped) = raw.find('.') {
                let trimmed = raw[stripped..]
                    .trim_end_matches('0')
                    .trim_end_matches('.');
                if trimmed.is_empty() {
                    raw[..stripped].to_string()
                } else {
                    format!("{}{}", &raw[..stripped], trimmed)
                }
            } else {
                raw
            }
        }
        _ => {
            // 'f' and anything else (treat unknown as f, since the
            // dominant use case is decimal coordinates).
            let s = format!("{value:.prec$}");
            if plus_sign && value >= 0.0 {
                format!("+{s}")
            } else {
                s
            }
        }
    };

    if width > body.len() {
        let pad = width - body.len();
        let ch = if zero_pad && !left_align { '0' } else { ' ' };
        let padding: String = std::iter::repeat(ch).take(pad).collect();
        body = if left_align {
            format!("{body}{padding}")
        } else {
            format!("{padding}{body}")
        };
    }

    format!("{prefix}{body}{suffix}")
}

impl PostProfile {
    /// Sensible LinuxCNC-compatible bundle. The hard-coded behavior
    /// is its baseline; this profile only sets the name so users can
    /// pick it from the dropdown without flipping any templates.
    #[must_use]
    pub fn linuxcnc_default() -> Self {
        Self {
            name: "LinuxCNC default".into(),
            file_extension: Some("nc".into()),
            line_ending: Some("\n".into()),
            ..Default::default()
        }
    }

    /// Mach3 metric bundle — `%` brackets, `.tap` extension, CRLF
    /// line endings.
    #[must_use]
    pub fn mach3_metric() -> Self {
        Self {
            name: "Mach3 metric".into(),
            file_extension: Some("tap".into()),
            line_ending: Some("\r\n".into()),
            program_start: Some("%\nN10 G21 G90 (wiac <version>)".into()),
            program_end: Some("M30\n%".into()),
            ..Default::default()
        }
    }

    /// GRBL bundle — semicolon comments, no toolchange semantics.
    #[must_use]
    pub fn grbl_default() -> Self {
        Self {
            name: "GRBL default".into(),
            file_extension: Some("nc".into()),
            line_ending: Some("\n".into()),
            program_start: Some("; wiac <version> — GRBL".into()),
            program_end: Some("M2".into()),
            tool_change: Some("; toolchange to T<t> (manual on GRBL)".into()),
            ..Default::default()
        }
    }
}

/// Token-substitution context. Carries the current tool / feed /
/// spindle / op state at the moment a template is rendered. The
/// pipeline drives this through `PostProcessor::set_token_ctx` at
/// program_begin and at each op boundary.
#[derive(Debug, Clone, Default)]
pub struct TokenCtx {
    pub tool_number: u32,
    pub tool_name: String,
    pub tool_diameter: f64,
    pub feed: u32,
    pub spindle: u32,
    pub op_name: String,
    pub unit: UnitSystem,
    pub version: String,
    pub tools_listing: String,
    pub project_name: String,
}

impl TokenCtx {
    /// Default that reads the wiac version from the CARGO_PKG env.
    /// Kept distinct from `Default` so the env lookup only happens
    /// on the explicit-call path.
    #[must_use]
    pub fn with_wiac_version() -> Self {
        Self {
            version: env!("CARGO_PKG_VERSION").to_string(),
            ..Default::default()
        }
    }
}

/// Replace token markers in `template` with their `ctx` values.
/// Tokens are case-insensitive `<name>` placeholders mirroring
/// Estlcam's `c_Gcode.cs` set:
/// - `<version>` — wiac version string
/// - `<unit>` — `mm` / `in`
/// - `<t>` / `<n>` / `<d>` — tool number / name / diameter
/// - `<f>` / `<s>` — feed (mm/min) / spindle (rpm)
/// - `<op>` — current operation name
/// - `<tools>` — full tool-library listing (one per line)
/// - `<project>` — project name (basename of the save file)
/// - `<nl>` — explicit newline (`\n`)
///
/// Unknown tokens pass through unchanged so a typo doesn't silently
/// blank the line; CAM-review surfaces them.
pub fn substitute(template: &str, ctx: &TokenCtx) -> String {
    let mut out = template.to_string();
    let unit = match ctx.unit {
        UnitSystem::Mm => "mm",
        UnitSystem::Inch => "in",
    };
    let pairs: [(&str, String); 11] = [
        ("<version>", ctx.version.clone()),
        ("<unit>", unit.to_string()),
        ("<t>", ctx.tool_number.to_string()),
        ("<n>", ctx.tool_name.clone()),
        ("<d>", format!("{:.3}", ctx.tool_diameter)),
        ("<f>", ctx.feed.to_string()),
        ("<s>", ctx.spindle.to_string()),
        ("<op>", ctx.op_name.clone()),
        ("<tools>", ctx.tools_listing.clone()),
        ("<project>", ctx.project_name.clone()),
        ("<nl>", "\n".to_string()),
    ];
    for (token, value) in pairs {
        // Case-insensitive replace.
        let mut buf = String::with_capacity(out.len());
        let token_lower = token.to_ascii_lowercase();
        let mut rest = out.as_str();
        loop {
            let pos = rest
                .char_indices()
                .find(|(i, _)| {
                    let end = i + token.len();
                    end <= rest.len()
                        && rest[*i..end].to_ascii_lowercase() == token_lower
                })
                .map(|(i, _)| i);
            match pos {
                Some(i) => {
                    buf.push_str(&rest[..i]);
                    buf.push_str(&value);
                    rest = &rest[i + token.len()..];
                }
                None => {
                    buf.push_str(rest);
                    break;
                }
            }
        }
        out = buf;
    }
    out
}

/// Split a multi-line substituted template into individual gcode
/// lines so the existing `PostProcessor::raw` / `write` paths see
/// one line at a time (line numbering / comment passes assume that).
#[must_use]
pub fn template_lines(template: &str, ctx: &TokenCtx) -> Vec<String> {
    substitute(template, ctx)
        .split('\n')
        .map(|s| s.to_string())
        .collect()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn substitute_replaces_basic_tokens() {
        let mut ctx = TokenCtx::default();
        ctx.tool_number = 7;
        ctx.tool_name = "3mm endmill".into();
        ctx.feed = 800;
        ctx.spindle = 18000;
        ctx.version = "0.1.0".into();
        let s = substitute("T<t> (<n>) F<f> S<s> wiac <version>", &ctx);
        assert_eq!(s, "T7 (3mm endmill) F800 S18000 wiac 0.1.0");
    }

    #[test]
    fn substitute_case_insensitive() {
        let mut ctx = TokenCtx::default();
        ctx.tool_number = 5;
        let s = substitute("<T> <t> <T>", &ctx);
        assert_eq!(s, "5 5 5");
    }

    #[test]
    fn substitute_unit_token() {
        let mut ctx = TokenCtx::default();
        ctx.unit = UnitSystem::Inch;
        assert_eq!(substitute("(unit: <unit>)", &ctx), "(unit: in)");
        ctx.unit = UnitSystem::Mm;
        assert_eq!(substitute("(unit: <unit>)", &ctx), "(unit: mm)");
    }

    #[test]
    fn substitute_unknown_token_passes_through() {
        let ctx = TokenCtx::default();
        let s = substitute("hello <unrecognized> world", &ctx);
        assert_eq!(s, "hello <unrecognized> world");
    }

    #[test]
    fn substitute_diameter_three_decimals() {
        let mut ctx = TokenCtx::default();
        ctx.tool_diameter = 3.175;
        assert_eq!(substitute("(d=<d>)", &ctx), "(d=3.175)");
    }

    #[test]
    fn template_lines_splits_on_explicit_newlines() {
        let ctx = TokenCtx::default();
        let v = template_lines("a\nb\nc", &ctx);
        assert_eq!(v, vec!["a", "b", "c"]);
    }

    #[test]
    fn template_lines_substitutes_nl_token_before_split() {
        let mut ctx = TokenCtx::default();
        ctx.tool_number = 2;
        let v = template_lines("T<t><nl>(start)", &ctx);
        assert_eq!(v, vec!["T2", "(start)"]);
    }

    #[test]
    fn profile_serde_round_trip() {
        let p = PostProfile {
            name: "Test".into(),
            program_start: Some("; hi".into()),
            tool_change: Some("T<t> M6 G43 H<t>".into()),
            ..Default::default()
        };
        let json = serde_json::to_string(&p).unwrap();
        let back: PostProfile = serde_json::from_str(&json).unwrap();
        assert_eq!(p, back);
    }

    #[test]
    fn unset_templates_omitted_from_json() {
        let p = PostProfile {
            name: "Minimal".into(),
            ..Default::default()
        };
        let json = serde_json::to_string(&p).unwrap();
        // Only `name` should be in the payload — every other field is
        // Option::None and skipped.
        assert!(!json.contains("program_start"));
        assert!(!json.contains("tool_change"));
    }

    #[test]
    fn bundled_mach3_profile_has_percent_brackets() {
        let p = PostProfile::mach3_metric();
        assert!(p.program_start.as_ref().unwrap().starts_with('%'));
        assert!(p.program_end.as_ref().unwrap().ends_with('%'));
        assert_eq!(p.line_ending.as_deref(), Some("\r\n"));
    }

    // ─── axis formatting (hev) ────────────────────────────────────────

    #[test]
    fn format_axis_value_default_three_decimals() {
        assert_eq!(format_axis_value("%.3f", 1.234_56), "1.235");
        assert_eq!(format_axis_value("%.4f", 1.234_56), "1.2346");
        assert_eq!(format_axis_value("%.0f", 3.7), "4");
    }

    #[test]
    fn format_axis_value_empty_falls_back_to_three_decimals() {
        assert_eq!(format_axis_value("", 1.234_56), "1.235");
    }

    #[test]
    fn format_axis_value_no_percent_passes_through() {
        // A misconfigured spec gives a visible eyesore in the gcode so
        // the user notices, rather than silently emitting the value.
        assert_eq!(format_axis_value("oops", 1.234), "oops");
    }

    #[test]
    fn format_axis_value_integer_rounds() {
        assert_eq!(format_axis_value("%d", 3.7), "4");
        assert_eq!(format_axis_value("%d", 3.4), "3");
        assert_eq!(format_axis_value("%d", -2.6), "-3");
    }

    #[test]
    fn format_axis_value_general_drops_trailing_zeros() {
        // %g with default 3 decimals: 1.200 → "1.2", 1.000 → "1"
        assert_eq!(format_axis_value("%.3g", 1.2), "1.2");
        assert_eq!(format_axis_value("%.3g", 1.0), "1");
        assert_eq!(format_axis_value("%.3g", 1.234), "1.234");
    }

    #[test]
    fn format_axis_value_prefix_and_suffix_preserved() {
        // Some Heidenhain dialects bracket the value: `X +1.000`.
        // The literal prefix " +" survives via the prefix capture.
        assert_eq!(format_axis_value("[%.2f]", 1.234), "[1.23]");
    }

    #[test]
    fn format_axis_value_width_and_zero_pad() {
        assert_eq!(format_axis_value("%06.2f", 1.5), "001.50");
        assert_eq!(format_axis_value("%-6.2f", 1.5), "1.50  ");
    }

    #[test]
    fn format_axis_value_plus_sign() {
        assert_eq!(format_axis_value("%+.2f", 1.5), "+1.50");
        assert_eq!(format_axis_value("%+.2f", -1.5), "-1.50");
    }

    #[test]
    fn axis_format_render_applies_scale() {
        let af = AxisFormat {
            enabled: true,
            name: "Z".into(),
            format: "%.3f".into(),
            scale: -1.0,
        };
        assert_eq!(af.render(2.5).as_deref(), Some("Z-2.500"));
        assert_eq!(af.render(-1.0).as_deref(), Some("Z1.000"));
    }

    #[test]
    fn axis_format_render_skipped_when_disabled() {
        let af = AxisFormat {
            enabled: false,
            name: "Z".into(),
            format: "%.3f".into(),
            scale: 1.0,
        };
        assert!(af.render(1.0).is_none());
    }

    #[test]
    fn axis_format_render_rename_axis() {
        let mut af = AxisFormat::coord("X");
        af.name = "A".into();
        assert_eq!(af.render(45.0).as_deref(), Some("A45.000"));
    }

    #[test]
    fn axes_config_default_matches_legacy() {
        let a = AxesConfig::default();
        assert_eq!(a.x.render(1.0).as_deref(), Some("X1.000"));
        assert_eq!(a.feed.render(800.0).as_deref(), Some("F800"));
        assert_eq!(a.speed.render(18_000.0).as_deref(), Some("S18000"));
    }

    #[test]
    fn axes_config_serde_round_trip() {
        let mut a = AxesConfig::default();
        a.z.scale = -1.0;
        a.z.format = "%.4f".into();
        a.feed.name = "FEED".into();
        let json = serde_json::to_string(&a).unwrap();
        let back: AxesConfig = serde_json::from_str(&json).unwrap();
        assert_eq!(a, back);
    }

    #[test]
    fn post_profile_with_axes_serde_round_trip() {
        let mut p = PostProfile::linuxcnc_default();
        let mut axes = AxesConfig::default();
        axes.z.enabled = false;
        p.axes = Some(axes);
        let json = serde_json::to_string(&p).unwrap();
        let back: PostProfile = serde_json::from_str(&json).unwrap();
        assert_eq!(p, back);
        assert!(!back.axes.unwrap().z.enabled);
    }

    #[test]
    fn axis_format_enabled_default_true_when_field_missing() {
        // Backwards-compat: an older JSON that doesn't carry the
        // `enabled` field should round-trip as enabled=true.
        let json = r#"{"name":"X","format":"%.3f","scale":1.0}"#;
        let af: AxisFormat = serde_json::from_str(json).unwrap();
        assert!(af.enabled);
    }
}
