//! User-configurable post-processor profile (rt1.15).
//!
//! A `PostProfile` is a serde-friendly bundle of TEMPLATE STRINGS that
//! override the hard-coded headers / footers / toolchange / coolant
//! lines that the built-in `linuxcnc.rs` / `grbl.rs` emitters bake in.
//! Each template runs through [`substitute`] at emit time so the user
//! can reference the current tool / feed / spindle / op without
//! editing wiac source.
//!
//! Scope reminder: v1 doesn't expose per-axis name / format / scale /
//! enable — that surface is filed as a follow-up. v1 covers the most
//! common controller-quirk vector: prologue / epilogue / toolchange
//! and coolant strings that vary by controller (Mach / FANUC /
//! Siemens / Heidenhain / a home-rolled controller).

use schemars::JsonSchema;
use serde::{Deserialize, Serialize};

use crate::cam::setup::UnitSystem;

/// A named bundle of override templates the user attaches to a
/// machine config. Any field left at `None` keeps the built-in
/// emitter's default behavior. The active variant of
/// `PostProcessorKind` is unaffected — wiac's linuxcnc / grbl / hpgl
/// emitters continue to drive line-level formatting (delta encoding,
/// arc fitting, drill cycles). The profile only swaps the
/// PROGRAM-LEVEL strings.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize, JsonSchema)]
pub struct PostProfile {
    /// User-facing label. Shown in MachineDialog's profile picker;
    /// not interpreted by the engine.
    #[serde(default)]
    pub name: String,
    /// File extension for save-to-disk (no leading dot). Default
    /// `"nc"`. Mach3 commonly uses `"tap"`, GRBL stays `"nc"`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub file_extension: Option<String>,
    /// Line separator on save. None ⇒ `"\n"`. Set to `"\r\n"` for
    /// FANUC / vintage Windows-y controllers.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub line_ending: Option<String>,
    /// PROGRAM_START template. Replaces the `(generated by …)`
    /// header line. Can contain multiple `\n`-separated lines via
    /// the `<NL>` token.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub program_start: Option<String>,
    /// PROGRAM_END template. Replaces the `M30` footer line.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub program_end: Option<String>,
    /// TOOL_CHANGE template. Replaces the `T<n> M6` toolchange line.
    /// Substitution context exposes the FUTURE tool's metadata.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub tool_change: Option<String>,
    /// COOLANT_FLOOD ON / OFF templates. Replace `M8` / `M9`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub coolant_flood_on: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub coolant_flood_off: Option<String>,
    /// COOLANT_MIST ON / OFF templates. Replace `M7` / `M9`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub coolant_mist_on: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub coolant_mist_off: Option<String>,
}

impl PostProfile {
    /// Sensible LinuxCNC-compatible bundle. The hard-coded behavior
    /// is its baseline; this profile only sets the name so users can
    /// pick it from the dropdown without flipping any templates.
    #[must_use]
    pub fn linuxcnc_default() -> Self {
        Self {
            name: "LinuxCNC default".into(),
            file_extension: Some("nc".into()),
            line_ending: Some("\n".into()),
            ..Default::default()
        }
    }

    /// Mach3 metric bundle — `%` brackets, `.tap` extension, CRLF
    /// line endings.
    #[must_use]
    pub fn mach3_metric() -> Self {
        Self {
            name: "Mach3 metric".into(),
            file_extension: Some("tap".into()),
            line_ending: Some("\r\n".into()),
            program_start: Some("%\nN10 G21 G90 (wiac <version>)".into()),
            program_end: Some("M30\n%".into()),
            ..Default::default()
        }
    }

    /// GRBL bundle — semicolon comments, no toolchange semantics.
    #[must_use]
    pub fn grbl_default() -> Self {
        Self {
            name: "GRBL default".into(),
            file_extension: Some("nc".into()),
            line_ending: Some("\n".into()),
            program_start: Some("; wiac <version> — GRBL".into()),
            program_end: Some("M2".into()),
            tool_change: Some("; toolchange to T<t> (manual on GRBL)".into()),
            ..Default::default()
        }
    }
}

/// Token-substitution context. Carries the current tool / feed /
/// spindle / op state at the moment a template is rendered. The
/// pipeline drives this through `PostProcessor::set_token_ctx` at
/// program_begin and at each op boundary.
#[derive(Debug, Clone, Default)]
pub struct TokenCtx {
    pub tool_number: u32,
    pub tool_name: String,
    pub tool_diameter: f64,
    pub feed: u32,
    pub spindle: u32,
    pub op_name: String,
    pub unit: UnitSystem,
    pub version: String,
    pub tools_listing: String,
    pub project_name: String,
}

impl TokenCtx {
    /// Default that reads the wiac version from the CARGO_PKG env.
    /// Kept distinct from `Default` so the env lookup only happens
    /// on the explicit-call path.
    #[must_use]
    pub fn with_wiac_version() -> Self {
        Self {
            version: env!("CARGO_PKG_VERSION").to_string(),
            ..Default::default()
        }
    }
}

/// Replace token markers in `template` with their `ctx` values.
/// Tokens are case-insensitive `<name>` placeholders mirroring
/// Estlcam's `c_Gcode.cs` set:
/// - `<version>` — wiac version string
/// - `<unit>` — `mm` / `in`
/// - `<t>` / `<n>` / `<d>` — tool number / name / diameter
/// - `<f>` / `<s>` — feed (mm/min) / spindle (rpm)
/// - `<op>` — current operation name
/// - `<tools>` — full tool-library listing (one per line)
/// - `<project>` — project name (basename of the save file)
/// - `<nl>` — explicit newline (`\n`)
///
/// Unknown tokens pass through unchanged so a typo doesn't silently
/// blank the line; CAM-review surfaces them.
pub fn substitute(template: &str, ctx: &TokenCtx) -> String {
    let mut out = template.to_string();
    let unit = match ctx.unit {
        UnitSystem::Mm => "mm",
        UnitSystem::Inch => "in",
    };
    let pairs: [(&str, String); 11] = [
        ("<version>", ctx.version.clone()),
        ("<unit>", unit.to_string()),
        ("<t>", ctx.tool_number.to_string()),
        ("<n>", ctx.tool_name.clone()),
        ("<d>", format!("{:.3}", ctx.tool_diameter)),
        ("<f>", ctx.feed.to_string()),
        ("<s>", ctx.spindle.to_string()),
        ("<op>", ctx.op_name.clone()),
        ("<tools>", ctx.tools_listing.clone()),
        ("<project>", ctx.project_name.clone()),
        ("<nl>", "\n".to_string()),
    ];
    for (token, value) in pairs {
        // Case-insensitive replace.
        let mut buf = String::with_capacity(out.len());
        let token_lower = token.to_ascii_lowercase();
        let mut rest = out.as_str();
        loop {
            let pos = rest
                .char_indices()
                .find(|(i, _)| {
                    let end = i + token.len();
                    end <= rest.len()
                        && rest[*i..end].to_ascii_lowercase() == token_lower
                })
                .map(|(i, _)| i);
            match pos {
                Some(i) => {
                    buf.push_str(&rest[..i]);
                    buf.push_str(&value);
                    rest = &rest[i + token.len()..];
                }
                None => {
                    buf.push_str(rest);
                    break;
                }
            }
        }
        out = buf;
    }
    out
}

/// Split a multi-line substituted template into individual gcode
/// lines so the existing `PostProcessor::raw` / `write` paths see
/// one line at a time (line numbering / comment passes assume that).
#[must_use]
pub fn template_lines(template: &str, ctx: &TokenCtx) -> Vec<String> {
    substitute(template, ctx)
        .split('\n')
        .map(|s| s.to_string())
        .collect()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn substitute_replaces_basic_tokens() {
        let mut ctx = TokenCtx::default();
        ctx.tool_number = 7;
        ctx.tool_name = "3mm endmill".into();
        ctx.feed = 800;
        ctx.spindle = 18000;
        ctx.version = "0.1.0".into();
        let s = substitute("T<t> (<n>) F<f> S<s> wiac <version>", &ctx);
        assert_eq!(s, "T7 (3mm endmill) F800 S18000 wiac 0.1.0");
    }

    #[test]
    fn substitute_case_insensitive() {
        let mut ctx = TokenCtx::default();
        ctx.tool_number = 5;
        let s = substitute("<T> <t> <T>", &ctx);
        assert_eq!(s, "5 5 5");
    }

    #[test]
    fn substitute_unit_token() {
        let mut ctx = TokenCtx::default();
        ctx.unit = UnitSystem::Inch;
        assert_eq!(substitute("(unit: <unit>)", &ctx), "(unit: in)");
        ctx.unit = UnitSystem::Mm;
        assert_eq!(substitute("(unit: <unit>)", &ctx), "(unit: mm)");
    }

    #[test]
    fn substitute_unknown_token_passes_through() {
        let ctx = TokenCtx::default();
        let s = substitute("hello <unrecognized> world", &ctx);
        assert_eq!(s, "hello <unrecognized> world");
    }

    #[test]
    fn substitute_diameter_three_decimals() {
        let mut ctx = TokenCtx::default();
        ctx.tool_diameter = 3.175;
        assert_eq!(substitute("(d=<d>)", &ctx), "(d=3.175)");
    }

    #[test]
    fn template_lines_splits_on_explicit_newlines() {
        let ctx = TokenCtx::default();
        let v = template_lines("a\nb\nc", &ctx);
        assert_eq!(v, vec!["a", "b", "c"]);
    }

    #[test]
    fn template_lines_substitutes_nl_token_before_split() {
        let mut ctx = TokenCtx::default();
        ctx.tool_number = 2;
        let v = template_lines("T<t><nl>(start)", &ctx);
        assert_eq!(v, vec!["T2", "(start)"]);
    }

    #[test]
    fn profile_serde_round_trip() {
        let p = PostProfile {
            name: "Test".into(),
            program_start: Some("; hi".into()),
            tool_change: Some("T<t> M6 G43 H<t>".into()),
            ..Default::default()
        };
        let json = serde_json::to_string(&p).unwrap();
        let back: PostProfile = serde_json::from_str(&json).unwrap();
        assert_eq!(p, back);
    }

    #[test]
    fn unset_templates_omitted_from_json() {
        let p = PostProfile {
            name: "Minimal".into(),
            ..Default::default()
        };
        let json = serde_json::to_string(&p).unwrap();
        // Only `name` should be in the payload — every other field is
        // Option::None and skipped.
        assert!(!json.contains("program_start"));
        assert!(!json.contains("tool_change"));
    }

    #[test]
    fn bundled_mach3_profile_has_percent_brackets() {
        let p = PostProfile::mach3_metric();
        assert!(p.program_start.as_ref().unwrap().starts_with('%'));
        assert!(p.program_end.as_ref().unwrap().ends_with('%'));
        assert_eq!(p.line_ending.as_deref(), Some("\r\n"));
    }
}
