// Generate `src/lib/i18n/keys.ts` from the English message catalog.
//
// `messages/en.json` is the SOURCE OF TRUTH for translatable keys. This
// script turns its key set into a TypeScript union (`MsgKey`) so every
// `t('…')` call site is type-checked: a typo'd or removed key becomes a
// `svelte-check` error instead of a silent runtime fallback. It mirrors the
// OpenAPI `codegen` drift-guard pattern (regenerate + `git diff --exit-code`
// in CI) — see .github/workflows/ci.yml.
//
// Node built-ins only — no dependency. Run via `pnpm run i18n:codegen`.
//
// Usage:
//   node scripts/i18n-codegen.mjs            # regenerate keys.ts
//   node scripts/i18n-codegen.mjs --report   # print per-locale coverage
//                                            #   (missing / extra / empty)

import { readFileSync, writeFileSync, readdirSync } from 'node:fs';
import { join, dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const TAG = '[i18n-codegen]';
// frontend/scripts/ → frontend/src/lib/i18n
const i18nDir = resolve(dirname(fileURLToPath(import.meta.url)), '../src/lib/i18n');
const messagesDir = join(i18nDir, 'messages');
const basePath = join(messagesDir, 'en.json');
const keysPath = join(i18nDir, 'keys.ts');

/** Parse a catalog file, failing loudly on malformed JSON. */
function readCatalog(file) {
  const raw = readFileSync(file, 'utf8');
  const parsed = JSON.parse(raw);
  if (parsed === null || typeof parsed !== 'object' || Array.isArray(parsed)) {
    throw new Error(`${file} must be a flat JSON object of key → string`);
  }
  return parsed;
}

const base = readCatalog(basePath);
const baseKeys = Object.keys(base).sort();

if (process.argv.includes('--report')) {
  // Translator-facing coverage report. Informational (exit 0); the
  // enforcing parity test lives in the coverage-tests issue (ivac-os2k.5).
  const locales = readdirSync(messagesDir)
    .filter((f) => f.endsWith('.json') && f !== 'en.json')
    .sort();
  if (locales.length === 0) {
    console.log(`${TAG} no non-base locales found in ${messagesDir}`);
  }
  const baseSet = new Set(baseKeys);
  for (const file of locales) {
    const cat = readCatalog(join(messagesDir, file));
    const keys = Object.keys(cat);
    const have = new Set(keys);
    const missing = baseKeys.filter((k) => !have.has(k));
    const extra = keys.filter((k) => !baseSet.has(k)).sort();
    const empty = keys.filter((k) => baseSet.has(k) && cat[k] === '').sort();
    const ok = missing.length === 0 && extra.length === 0 && empty.length === 0;
    console.log(
      `${TAG} ${file}: ${baseKeys.length - missing.length}/${baseKeys.length} translated` +
        (ok ? ' ✓' : ''),
    );
    if (missing.length) console.log(`  missing (${missing.length}): ${missing.join(', ')}`);
    if (extra.length) console.log(`  extra   (${extra.length}): ${extra.join(', ')}`);
    if (empty.length) console.log(`  empty   (${empty.length}): ${empty.join(', ')}`);
  }
  process.exit(0);
}

const body =
  baseKeys.length === 0 ? '  never' : baseKeys.map((k) => `  | ${JSON.stringify(k)}`).join('\n');

const out = `// GENERATED by scripts/i18n-codegen.mjs from messages/en.json — DO NOT EDIT.
// Run \`pnpm run i18n:codegen\` after changing en.json. CI guards this with
// \`git diff --exit-code\` (see .github/workflows/ci.yml).

/** Every translatable message key, derived from the English base catalog. */
export type MsgKey =
${body};

/** All keys as an array (handy for coverage tests / iteration). */
export const MSG_KEYS: readonly MsgKey[] = [
${baseKeys.map((k) => `  ${JSON.stringify(k)},`).join('\n')}
];
`;

writeFileSync(keysPath, out);
console.log(`${TAG} wrote ${keysPath} (${baseKeys.length} keys)`);
