/// Unit tests for the TS post-profile preview helpers (uzz). Avoids
/// importing from `project.svelte` so this test file stays in the
/// logic-only (no-svelte-runtime) vitest config.

import { describe, expect, it } from 'vitest';
import type { AxesConfig, AxisFormat, PostProfile } from '../state/project.svelte';
import {
  defaultPreviewCtx,
  formatAxisValue,
  previewGcode,
  renderAxisWord,
  substitute,
} from './post-profile-preview';

function defaultAxesConfig(): AxesConfig {
  const coord = (name: string): AxisFormat => ({
    enabled: true,
    name,
    format: '%.3f',
    scale: 1.0,
  });
  const int = (name: string): AxisFormat => ({
    enabled: true,
    name,
    format: '%d',
    scale: 1.0,
  });
  return {
    x: coord('X'),
    y: coord('Y'),
    z: coord('Z'),
    i: coord('I'),
    j: coord('J'),
    feed: int('F'),
    speed: int('S'),
  };
}

describe('substitute', () => {
  it('replaces every basic token', () => {
    const ctx = defaultPreviewCtx();
    ctx.toolNumber = 7;
    ctx.toolName = '3mm endmill';
    ctx.feed = 800;
    ctx.spindle = 18000;
    ctx.version = '0.2.3';
    expect(substitute('T<t> (<n>) F<f> S<s> ivac <version>', ctx)).toBe(
      'T7 (3mm endmill) F800 S18000 ivac 0.2.3',
    );
  });

  it('is case-insensitive', () => {
    const ctx = defaultPreviewCtx();
    ctx.toolNumber = 5;
    expect(substitute('<T> <t> <T>', ctx)).toBe('5 5 5');
  });

  it('renders the unit token', () => {
    const ctx = defaultPreviewCtx();
    ctx.unit = 'in';
    expect(substitute('(unit: <unit>)', ctx)).toBe('(unit: in)');
    ctx.unit = 'mm';
    expect(substitute('(unit: <unit>)', ctx)).toBe('(unit: mm)');
  });

  it('passes unknown tokens through unchanged', () => {
    expect(substitute('hi <bogus> there', defaultPreviewCtx())).toBe('hi <bogus> there');
  });

  it('substitutes <nl> as a newline', () => {
    expect(substitute('a<nl>b', defaultPreviewCtx())).toBe('a\nb');
  });
});

describe('formatAxisValue', () => {
  it('renders %.3f by default for empty format', () => {
    expect(formatAxisValue('', 1.23456)).toBe('1.235');
  });

  it('honors the precision', () => {
    expect(formatAxisValue('%.3f', 1.23456)).toBe('1.235');
    expect(formatAxisValue('%.4f', 1.23456)).toBe('1.2346');
    expect(formatAxisValue('%.0f', 3.7)).toBe('4');
  });

  it('renders integer with %d', () => {
    expect(formatAxisValue('%d', 3.7)).toBe('4');
    expect(formatAxisValue('%d', -2.6)).toBe('-3');
  });

  it('drops trailing zeros for %g', () => {
    expect(formatAxisValue('%.3g', 1.2)).toBe('1.2');
    expect(formatAxisValue('%.3g', 1.0)).toBe('1');
  });

  it('zero-pads with width', () => {
    expect(formatAxisValue('%06.2f', 1.5)).toBe('001.50');
  });

  it('preserves prefix/suffix outside the % spec', () => {
    expect(formatAxisValue('[%.2f]', 1.234)).toBe('[1.23]');
  });

  it('passes through a string with no % anywhere', () => {
    expect(formatAxisValue('oops', 1.2)).toBe('oops');
  });
});

describe('renderAxisWord', () => {
  it('falls back to default letter + format when axis is undefined', () => {
    // JS `toFixed` rounds half-to-even and 1.2345 is actually
    // ~1.23449999… in IEEE-754, so pick a value whose rounding is
    // unambiguous.
    expect(renderAxisWord(undefined, 'X', 1.2378, '%.3f')).toBe('X1.238');
  });

  it('uses the axis name when given', () => {
    expect(
      renderAxisWord({ enabled: true, name: 'A', format: '%.3f', scale: 1.0 }, 'X', 45.0, '%.3f'),
    ).toBe('A45.000');
  });

  it('applies scale before formatting', () => {
    expect(
      renderAxisWord({ enabled: true, name: 'Z', format: '%.3f', scale: -1.0 }, 'Z', 2.5, '%.3f'),
    ).toBe('Z-2.500');
  });

  it('returns null when disabled', () => {
    expect(
      renderAxisWord({ enabled: false, name: 'Z', format: '%.3f', scale: 1.0 }, 'Z', 1.0, '%.3f'),
    ).toBeNull();
  });
});

describe('previewGcode', () => {
  it('falls back to ivac defaults for an empty profile', () => {
    const out = previewGcode({});
    expect(out).toContain('(generated by ivaCAM)');
    expect(out).toContain('G21'); // mm
    expect(out).toContain('G0 X10.000 Y10.000 Z3.000');
    // Arc line carries Z plus I/J (the preview doesn't dedupe like
    // the real pipeline does).
    expect(out).toContain('G2 X20.000 Y10.000 Z-2.000 I5.000 J0.000');
    expect(out).toContain('M30');
  });

  it('substitutes tokens in custom program_start / _end', () => {
    const profile: PostProfile = {
      program_start: '; ivac <version> for <n>',
      program_end: '; bye <project>',
    };
    const out = previewGcode(profile);
    expect(out).toContain('; ivac 0.1.0 for 3mm endmill');
    expect(out).toContain('; bye preview');
    // Default LinuxCNC header is gone when a custom one is set.
    expect(out).not.toContain('(generated by ivaCAM)');
  });

  it('renames Y to V when axes config says so', () => {
    const axes = defaultAxesConfig();
    axes.y.name = 'V';
    const out = previewGcode({ axes });
    expect(out).toMatch(/G0 X10\.000 V10\.000 Z3\.000/);
  });

  it('flips Z when scale = -1', () => {
    const axes = defaultAxesConfig();
    axes.z.scale = -1.0;
    const out = previewGcode({ axes });
    // G1 carries Z-2 in source units; with scale=-1, the rendered Z
    // becomes positive.
    expect(out).toMatch(/G1 X10\.000 Y10\.000 Z2\.000/);
    // G0 carries Z=3 source ⇒ Z-3 rendered.
    expect(out).toMatch(/G0 X10\.000 Y10\.000 Z-3\.000/);
  });

  it('drops disabled axes from every line', () => {
    const axes = defaultAxesConfig();
    axes.z.enabled = false;
    const out = previewGcode({ axes });
    const bad = out.split('\n').filter((l) => /^G[01].*Z/.test(l));
    expect(bad).toEqual([]);
  });

  it('formats feed with the configured precision', () => {
    const axes = defaultAxesConfig();
    axes.feed.format = '%.2f';
    const out = previewGcode({ axes });
    expect(out).toContain('F800.00');
  });

  it('marks CRLF line endings visibly in the preview', () => {
    const out = previewGcode({ line_ending: '\r\n', program_start: '; hi' });
    expect(out).toContain('↵');
  });
});
