// GENERATED by scripts/i18n-codegen.mjs from messages/en.json — DO NOT EDIT.
// Run `pnpm run i18n:codegen` after changing en.json. CI guards this with
// `git diff --exit-code` (see .github/workflows/ci.yml).

/** Every translatable message key, derived from the English base catalog. */
export type MsgKey =
  | "settings.appearance.language"
  | "settings.appearance.language.auto"
  | "settings.appearance.language.help";

/** All keys as an array (handy for coverage tests / iteration). */
export const MSG_KEYS: readonly MsgKey[] = [
  "settings.appearance.language",
  "settings.appearance.language.auto",
  "settings.appearance.language.help",
];
