/// Pure serializer for the project report → Markdown with YAML front
/// matter. Kept out of ReportDialog.svelte so vitest can cover
/// the formatting (escaping, front matter, tables) without mounting the
/// dialog. The dialog assembles `ReportData` from project state and
/// hands it here.

export interface ReportTool {
  name: string;
  kind: string;
  diameterMm: number;
}

export interface ReportOp {
  name: string;
  kind: string;
  tool: string;
  source: string;
  depth: string;
  status: string;
}

export interface ReportData {
  projectName: string;
  /// Full version string, e.g. "ivaCAM v0.0.0 (abc1234, built 2026-05-25T…)".
  generatedBy: string;
  dateIso: string;
  dateDisplay: string;
  stats: { objects: number; offsets: number; segments: number; enabledOps: number } | null;
  estimatedTime: string | null;
  tools: ReportTool[];
  ops: ReportOp[];
  warnings: { bad: number; warn: number; top: { kind: string; message: string }[] };
}

/// Quote + escape a value for a YAML double-quoted scalar.
function yamlStr(v: string): string {
  return `"${v.replace(/\\/g, '\\\\').replace(/"/g, '\\"')}"`;
}

/// Escape a Markdown table cell — pipes would otherwise split columns,
/// newlines would break the row.
function cell(v: string): string {
  return v.replace(/\|/g, '\\|').replace(/\r?\n/g, ' ');
}

export function buildReportMarkdown(d: ReportData): string {
  const fm: string[] = ['---'];
  fm.push(`title: ${yamlStr(d.projectName)}`);
  fm.push(`generated_by: ${yamlStr(d.generatedBy)}`);
  fm.push(`date: ${yamlStr(d.dateIso)}`);
  if (d.stats) {
    fm.push(`objects: ${d.stats.objects}`);
    fm.push(`enabled_ops: ${d.stats.enabledOps}`);
  }
  fm.push(`tools: ${d.tools.length}`);
  if (d.estimatedTime) fm.push(`estimated_time: ${yamlStr(d.estimatedTime)}`);
  fm.push('---', '');

  const body: string[] = [];
  body.push(`# ${d.projectName}`, '');
  body.push(`_${d.dateDisplay} · ivaCAM report_`, '');

  if (d.stats) {
    body.push('## Toolpath stats', '');
    body.push('| Metric | Value |', '| --- | --- |');
    body.push(`| Objects | ${d.stats.objects} |`);
    body.push(`| Offsets | ${d.stats.offsets} |`);
    body.push(`| Toolpath segments | ${d.stats.segments} |`);
    body.push(`| Enabled ops | ${d.stats.enabledOps} |`);
    if (d.estimatedTime) body.push(`| Estimated time | ${cell(d.estimatedTime)} |`);
    body.push('');
  }

  if (d.tools.length > 0) {
    body.push('## Tools', '');
    body.push('| Tool | Kind | Ø (mm) |', '| --- | --- | --- |');
    for (const t of d.tools) {
      body.push(`| ${cell(t.name)} | ${cell(t.kind)} | ${t.diameterMm.toFixed(2)} |`);
    }
    body.push('');
  }

  if (d.ops.length > 0) {
    body.push('## Operations', '');
    body.push(
      '| Op | Kind | Tool | Source | Depth | Status |',
      '| --- | --- | --- | --- | --- | --- |',
    );
    for (const o of d.ops) {
      body.push(
        `| ${cell(o.name)} | ${cell(o.kind)} | ${cell(o.tool)} | ${cell(o.source)} | ${cell(o.depth)} | ${cell(o.status)} |`,
      );
    }
    body.push('');
  }

  if (d.warnings.bad + d.warnings.warn > 0) {
    body.push('## Warnings', '');
    body.push(`**${d.warnings.bad} critical · ${d.warnings.warn} non-critical**`, '');
    for (const w of d.warnings.top) {
      body.push(`- **${cell(w.kind)}** — ${cell(w.message)}`);
    }
    body.push('');
  }

  body.push('---', `_Generated by ${d.generatedBy}_`, '');

  return fm.join('\n') + body.join('\n');
}
