import { describe, expect, it } from 'vitest';
import { buildReportMarkdown, type ReportData } from './report-markdown';

function base(): ReportData {
  return {
    projectName: 'bracket.dxf',
    generatedBy: 'wiaConstructor v0.0.0 (abc1234, built 2026-05-25T10:00:00Z)',
    dateIso: '2026-05-25T10:00:00.000Z',
    dateDisplay: '5/25/2026, 10:00:00 AM',
    stats: { objects: 3, offsets: 5, segments: 240, enabledOps: 2 },
    estimatedTime: '00:12:34',
    tools: [{ name: '3mm flat', kind: 'endmill', diameterMm: 3 }],
    ops: [
      { name: 'Profile', kind: 'profile', tool: '3mm flat', source: 'all geometry', depth: '-5.00 mm', status: 'ok' },
    ],
    warnings: { bad: 1, warn: 2, top: [{ kind: 'tool_too_large', message: 'tool wider than slot' }] },
  };
}

describe('buildReportMarkdown', () => {
  it('emits YAML front matter with the key fields', () => {
    const md = buildReportMarkdown(base());
    expect(md.startsWith('---\n')).toBe(true);
    expect(md).toContain('title: "bracket.dxf"');
    expect(md).toContain('generated_by: "wiaConstructor v0.0.0 (abc1234, built 2026-05-25T10:00:00Z)"');
    expect(md).toContain('date: "2026-05-25T10:00:00.000Z"');
    expect(md).toContain('objects: 3');
    expect(md).toContain('enabled_ops: 2');
    expect(md).toContain('tools: 1');
    expect(md).toContain('estimated_time: "00:12:34"');
    // front matter closes before the body
    expect(md.indexOf('---', 4)).toBeLessThan(md.indexOf('# bracket.dxf'));
  });

  it('uses the capital-C product name in the body + footer', () => {
    const md = buildReportMarkdown(base());
    expect(md).toContain('· wiaConstructor report_');
    expect(md).toContain('_Generated by wiaConstructor v0.0.0');
    expect(md).not.toMatch(/wiaconstructor/); // never the lowercase form
  });

  it('renders stats / tools / ops / warnings tables', () => {
    const md = buildReportMarkdown(base());
    expect(md).toContain('## Toolpath stats');
    expect(md).toContain('| Toolpath segments | 240 |');
    expect(md).toContain('## Tools');
    expect(md).toContain('| 3mm flat | endmill | 3.00 |');
    expect(md).toContain('## Operations');
    expect(md).toContain('| Profile | profile | 3mm flat | all geometry | -5.00 mm | ok |');
    expect(md).toContain('## Warnings');
    expect(md).toContain('**1 critical · 2 non-critical**');
    expect(md).toContain('- **tool_too_large** — tool wider than slot');
  });

  it('escapes pipes in table cells so columns are not split', () => {
    const d = base();
    d.ops[0].source = 'layer "a|b"';
    const md = buildReportMarkdown(d);
    expect(md).toContain('layer "a\\|b"');
  });

  it('omits optional sections when empty', () => {
    const d = base();
    d.stats = null;
    d.estimatedTime = null;
    d.tools = [];
    d.ops = [];
    d.warnings = { bad: 0, warn: 0, top: [] };
    const md = buildReportMarkdown(d);
    expect(md).not.toContain('## Toolpath stats');
    expect(md).not.toContain('## Tools');
    expect(md).not.toContain('## Operations');
    expect(md).not.toContain('## Warnings');
    expect(md).not.toContain('estimated_time:');
    // still has title + generated-by footer
    expect(md).toContain('# bracket.dxf');
    expect(md).toContain('_Generated by ');
  });
});
